// Generated by CoffeeScript 1.3.1
(function() {

  Aria.classDefinition({
    $classpath: 'games.common.input.StandardKeyboardRecorder',
    $extends: 'games.common.BaseObject',
    $implements: ['games.common.input.InputRecorder'],
    $dependencies: ['games.shoot.utils.Console'],
    $constructor: function(keyboardRecorder) {
      this.$BaseObject.constructor.call(this);
      this.keyboardRecorder = keyboardRecorder;
      return this;
    },
    $prototype: {
      start: function() {
        return this.keyboardRecorder.start();
      },
      stop: function() {
        return this.keyboardRecorder.stop();
      },
      update: function(time) {
        return this.keyboardRecorder.update(time);
      },
      getInputByCode: function(code) {
        var input;
        input = this.keyboardRecorder.getInputByCode(this.translateToDeviceCode(code));
        if (input != null) {
          return input;
        }
      },
      translateToDeviceCode: function(code) {
        switch (code) {
          case 'ENTER':
            return 'KEYBOARD_13';
          case 'P':
            return 'KEYBOARD_80';
          case 'R':
            return 'KEYBOARD_82';
        }
      }
    }
  });

}).call(this);
