// Generated by CoffeeScript 1.3.1
(function() {

  Aria.classDefinition({
    $classpath: 'games.common.input.TouchInputRecorder',
    $extends: 'games.common.input.BasicInputRecorder',
    $dependencies: ['aria.utils.Event', 'aria.core.Timer', 'games.shoot.utils.Console', 'games.common.input.DefaultInput'],
    $constructor: function() {
      this.$BasicInputRecorder.constructor.call(this);
      this.gameContainer = document.getElementById("gameContainer");
      return this;
    },
    $prototype: {
      start: function() {
        this.$Event.addListener(this.gameContainer, "touchstart", {
          fn: this.onTouchStart,
          scope: this
        });
        this.$Event.addListener(document, "touchend", {
          fn: this.onTouchEnd,
          scope: this
        });
        this.$Event.addListener(document, "touchmove", {
          fn: this.onTouchMove,
          scope: this
        });
        return this.$Event.addListener(window, "devicemotion", {
          fn: this.onDeviceMotion,
          scope: this
        });
      },
      stop: function() {
        this.$Event.removeListener(this.gameContainer, "touchstart", {
          fn: this.onTouchStart,
          scope: this
        });
        return this.$Event.removeListener(this.gameContainer, "touchend", {
          fn: this.onTouchEnd,
          scope: this
        });
      },
      onDeviceMotion: function(event) {
        var acceleration, input;
        acceleration = event.accelerationIncludingGravity;
        input = this.getInputByCode('MOVE');
        if (!input) {
          input = new this.$DefaultInput('MOVE', this._currentGameTime);
          this.addInputAndPrevent(input, event);
        }
        input.x = acceleration.x;
        input.y = acceleration.y;
        input.z = acceleration.z;
        return event.preventDefault();
      },
      onTouchEnd: function(evt) {
        var input;
        switch (evt.touches.length) {
          case 0:
            input = this.getInputByCode('TAP');
            if (input) {
              input.complete();
            }
            break;
          case 1:
            input = this.getInputByCode('DOUBLETAP');
            if (input) {
              input.complete();
            }
        }
        return event.preventDefault();
      },
      onTouchStart: function(evt) {
        var input;
        if (evt.touches.length === 2) {
          input = new this.$DefaultInput('DOUBLETAP', this._currentGameTime);
        } else if (evt.touches.length === 1) {
          input = new this.$DefaultInput('TAP', this._currentGameTime);
        }
        if (!this.getInputByCode(input.getCode())) {
          return this.addInputAndPrevent(input, evt);
        }
      },
      onTouchMove: function(event) {
        return event.preventDefault();
      },
      addInputAndPrevent: function(input, event) {
        this.addInput(input);
        return event.preventDefault();
      }
    }
  });

}).call(this);
