// Generated by CoffeeScript 1.3.1
(function() {

  Aria.classDefinition({
    $classpath: 'games.shoot.clock.StatsAwareEngineClock',
    $extends: 'games.common.clock.EngineClock',
    $constructor: function(engine, animationLoop, statsRecorder) {
      this.$EngineClock.constructor.call(this, engine, animationLoop);
      this.statsRecorder = statsRecorder;
      this.statsTool = this.createStatsTool();
      return this;
    },
    $prototype: {
      createStatsTool: function() {
        var stats;
        stats = new Stats;
        stats.setMode(0);
        stats.domElement.style.position = 'absolute';
        stats.domElement.style.left = '0px';
        stats.domElement.style.top = '0px';
        document.body.appendChild(stats.domElement);
        return stats;
      },
      onLoop: function() {
        var beginTimestamp;
        this.statsTool.begin();
        beginTimestamp = Date.now();
        this.$EngineClock.onLoop.call(this);
        this.statsTool.end();
        return this.statsRecorder.updateTime("loop", Date.now() - beginTimestamp);
      }
    }
  });

}).call(this);
