// Generated by CoffeeScript 1.3.1
(function() {

  Aria.classDefinition({
    $classpath: 'games.audio.Assets',
    $singleton: true,
    $constructor: function() {
      return ['soundGenerator.png'];
    }
  });

}).call(this);
