// Generated by CoffeeScript 1.3.1
(function() {

  Aria.classDefinition({
    $classpath: 'games.shoot.engine.ExtendedEngine',
    $extends: 'games.common.BaseObject',
    $implements: ['games.common.engine.Engine'],
    $dependencies: ['games.common.clock.Timer', 'games.common.engine.GameEngine'],
    $statics: {
      getDefaultImplementation: function(context) {
        var baseEngine, timer;
        timer = new games.common.clock.Timer(16);
        baseEngine = new games.common.engine.GameEngine(context, timer);
        return new games.shoot.engine.ExtendedEngine(baseEngine);
      }
    },
    $constructor: function(baseEngine) {
      this.baseEngine = baseEngine;
      this.controllers = [];
      return this;
    },
    $prototype: {
      getEntities: function() {
        return this.baseEngine.getEntities();
      },
      setEntities: function(entities) {
        return this.baseEngine.setEntities(entities);
      },
      getTimer: function() {
        return this.baseEngine.getTimer();
      },
      addEntity: function(entity) {
        return this.baseEngine.addEntity(entity);
      },
      addController: function(controller) {
        return this.controllers.push(controller);
      },
      update: function() {
        var controller, _i, _len, _ref;
        _ref = this.controllers;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          controller = _ref[_i];
          controller.update();
        }
        return this.baseEngine.update();
      },
      draw: function() {
        return this.baseEngine.draw();
      }
    }
  });

}).call(this);
