// Generated by CoffeeScript 1.3.1
(function() {

  Aria.classDefinition({
    $classpath: 'games.shoot.ship.ShipPilot',
    $extends: 'games.common.BaseObject',
    $dependencies: ['games.shoot.ship.ShipInputRecorder', 'games.shoot.utils.RecorderFactory'],
    $constructor: function(ship) {
      this.$BaseObject.constructor.call(this);
      this.ship = ship;
      this.totalTime = 0;
      this.recorder = this.createInputRecorder();
      this.recorder.start();
      return this;
    },
    $prototype: {
      update: function(deltaTime) {
        var movementOrders;
        this.totalTime += deltaTime;
        this.recorder.update();
        if (this.recorder.getInputByCode("fireBullet")) {
          this.ship.fire(deltaTime);
        } else {
          this.ship.haltFire(deltaTime);
        }
        movementOrders = {
          up: this.recorder.getInputByCode("up") ? 1 : 0,
          down: this.recorder.getInputByCode("down") ? 1 : 0,
          left: this.recorder.getInputByCode("left") ? 1 : 0,
          right: this.recorder.getInputByCode("right") ? 1 : 0
        };
        return this.ship.move(deltaTime, movementOrders);
      },
      createInputRecorder: function() {
        var kbRecorder;
        kbRecorder = this.$RecorderFactory.getKeyboardRecorder();
        return new this.$ShipInputRecorder(kbRecorder);
      }
    }
  });

}).call(this);
