// Generated by CoffeeScript 1.3.1
(function() {

  Aria.classDefinition({
    $classpath: 'games.shoot.ship.TouchShipPilot',
    $extends: 'games.common.BaseObject',
    $dependencies: ['games.shoot.utils.RecorderFactory'],
    $constructor: function(ship) {
      this.$BaseObject.constructor.call(this);
      this.ship = ship;
      this.totalTime = 0;
      this.recorder = this.$RecorderFactory.getTouchInputRecorder();
      this.recorder.start();
      return this;
    },
    $prototype: {
      update: function(deltaTime) {
        var moveInput, movementOrders, tapInput;
        this.totalTime += deltaTime;
        this.recorder.update();
        movementOrders = {
          right: 0,
          left: 0,
          up: 0,
          down: 0
        };
        tapInput = this.recorder.getInputByCode("TAP");
        if (tapInput) {
          this.ship.fire(deltaTime);
        } else {
          this.ship.haltFire(deltaTime);
        }
        moveInput = this.recorder.getInputByCode("MOVE");
        if (moveInput) {
          if (moveInput.x > 0) {
            movementOrders.right = 1;
          }
          if (moveInput.x < 0) {
            movementOrders.left = 1;
          }
          if (moveInput.y < -5) {
            movementOrders.down = 1;
          }
          if (moveInput.y > -5) {
            movementOrders.up = 1;
          }
        }
        return this.ship.move(deltaTime, movementOrders);
      }
    }
  });

}).call(this);
