// Generated by CoffeeScript 1.3.1
(function() {

  Aria.classDefinition({
    $classpath: 'games.shoot.utils.Console',
    $extends: 'games.common.BaseObject',
    $singleton: true,
    $constructor: function() {
      this.domElement = document.getElementById("htmlshoot-console");
      return this;
    },
    $prototype: {
      log: function(message) {
        var html;
        message = "<div>&gt;&nbsp;" + message + "</div>";
        html = this.domElement.innerHTML;
        return this.domElement.innerHTML = message + html;
      }
    }
  });

}).call(this);
