// Generated by CoffeeScript 1.3.1
(function() {

  Aria.classDefinition({
    $classpath: 'games.shoot.utils.Lol',
    $singleton: true,
    $constructor: function() {
      return this.ICANHAZ = window.location.href.indexOf('lol') !== -1;
    }
  });

}).call(this);
