/*
 * Copyright Amadeus
 */
//***MULTI-PART
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Callback.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.Callback",$constructor:function(a){a=this.$normCallback(a);this._scope=a.scope;this._function=a.fn;this._args=a.args},$destructor:function(){this._args=this._function=this._scope=null},$prototype:{call:function(a){return this._function.call(this._scope,a,this._args)}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/ClassList.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.ClassList",$constructor:function(a){this.setClassName=function(b){a.className=b};this.getClassName=function(){return a.className};this._dispose=function(){this._dispose=a=null}},$destructor:function(){this._dispose&&this._dispose()},$prototype:{add:function(a){this.contains(a)||this.setClassName(this.getClassName()+" "+a)},remove:function(a){for(var b=this.getClassName().split(" "),c=0,d=b.length;c<d;c++)if(b[c]==a){b.splice(c,1);break}this.setClassName(b.join(" "))},
toggle:function(a){this.contains(a)?this.remove(a):this.add(a)},contains:function(a){for(var b=this.getClassName().split(" "),c=0,d=b.length;c<d;c++)if(b[c]==a)return true;return false},setClassName:function(){},getClassName:function(){}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Data.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.Data",$extends:"aria.core.JsObject",$singleton:true,$dependencies:["aria.utils.Type","aria.utils.Path","aria.utils.Json"],$constructor:function(){this.utilsType=aria.utils.Type;this.utilsArray=aria.utils.Array},$statics:{NBROF_PREFIX:"nbrOf",META_PREFIX:Aria.FRAMEWORK_PREFIX+"meta::",TYPE_FATAL:"F",TYPE_ERROR:"E",TYPE_WARNING:"W",TYPE_INFO:"I",TYPE_NOTYPE:"N",TYPE_CRITICAL_WARNING:"C",TYPE_CONFIRMATION:"O",DATA_NO_PARAMETER_TO_CONTAINER:"Parameter %1 is not defined in container:",
RESOLVE_FAIL:"Resolve for path %1 failed, root element does not contain this path",INVALID_VALIDATOR_GROUP_PARAMETER:"The validation group parameter must be an array.",DATA_UTIL_ERROR_MESSAGE_WRONG_TYPE:"listOfMessages property has to be an array."},$prototype:{_getMeta:function(b,a,c){a=this.META_PREFIX+a;var d=b[a];if(!d){d={};if(c===false)b[a]=d;else aria.utils.Json.setValue(b,a,d)}return d},getValidator:function(b,a){var c=this._getMeta(b,a);if(!c)return null;return aria.utils.Json.getValue(c,
"validator")},getFrameworkMessage:function(b,a){var c=this._getMeta(b,a);if(this.utilsType.isArray(c.formatErrorMessages))return c.formatErrorMessages;return null},setValidatorProperties:function(b,a,c){if(c)b.eventToValidate=c;if(this.utilsType.isArray(a)&&a.length){c=0;for(var d;d=a[c];c++)b.groups.push(d)}else this.utilsType.isString(a)&&a!=null&&this.$logError(this.INVALID_VALIDATOR_GROUP_PARAMETER)},setValidator:function(b,a,c,d,e){this.setValidatorProperties(c,d,e);if((this.utilsType.isObject(b)||
this.utilsType.isArray(b))&&a in b){b=this._getMeta(b,a);aria.utils.Json.setValue(b,"validator",c)}else this.$logError(this.DATA_NO_PARAMETER_TO_CONTAINER,[a],b)},unsetValidator:function(b,a){this.setValidator(b,a)},createMessage:function(b,a,c,d,e){var g=this.TYPE_ERROR;b={errorMessage:b,type:c||g,localizedMessage:a||b,code:d||null};if(e)b.subMessages=e;return b},addMessage:function(b,a,c,d,e){var g=aria.utils.Json;e=e!==false;if(this.utilsType.isObject(a)){this._updateCounters(b,a);if(a.listOfMessages)this.utilsType.isArray(a.listOfMessages)||
this.$logError(this.DATA_UTIL_ERROR_MESSAGE_WRONG_TYPE);else a.listOfMessages=[];e&&a.listOfMessages.push(b);if(b.subMessages){e=0;for(var h;h=b.subMessages[e];e++)this.addMessage(h,a,null,null,false)}}if(c&&d){a=this._getMeta(c,d);c=g.copy(a.errorMessages);if(c==null)c=[b.localizedMessage];else c.push(b.localizedMessage);g.setValue(a,"errorMessages",c);g.setValue(a,"error",true)}},_updateCounters:function(b,a){var c=this.NBROF_PREFIX+b.type;if(a[c])a[c]++;else a[c]=1},_processMessagesArray:function(b,
a,c,d){for(var e,g=0;g<b.length;g++){e=b[g];this._updateCounters(e,a);e.metaDataRef=d;e.type==this.TYPE_ERROR&&c.push(e.localizedMessage);e.subMessages&&this._processMessagesArray(e.subMessages,a,c,d)}},checkGroup:function(b,a){if(a)if(this.utilsType.isString(a)&&a!=null)this.$logError(this.INVALID_VALIDATOR_GROUP_PARAMETER);else{if(this.utilsType.isArray(a)&&a.length)for(var c=0,d;d=a[c];c++)if(this.utilsArray.contains(b,d))return true}else return true;return false},checkEventToValidate:function(b,
a){return!a||b===a},validateValue:function(b,a,c,d,e){var g=this.getValidator(b,a),h=aria.utils.Json,j=this.getFrameworkMessage(b,a),k=j&&j.length,i=this._getMeta(b,a),l=false;if(g&&g.groups)l=(l=this.checkGroup(g.groups,d))&&this.checkEventToValidate(g.eventToValidate,e);var f;if(k)f=[this.createMessage(j[0])];else if(l)f=g.validate(b[a],d,e);if(f){c||(c={});b=[];this._processMessagesArray(f,c,b,i);c.listOfMessages=c.listOfMessages?c.listOfMessages.concat(f):f;if(!k){h.setValue(i,"errorMessages",
b);h.setValue(i,"error",b.length>0)}}else{h.setValue(i,"errorMessages",[]);h.setValue(i,"error",false)}return f},validateModel:function(b,a,c){if(this.utilsType.isObject(b))for(var d in b)b.hasOwnProperty(d)&&this.__subValidateModel(b,d,a,c);else if(this.utilsType.isArray(b)){d=0;for(var e=b.length;d<e;d++)this.__subValidateModel(b,d,a,c)}},__subValidateModel:function(b,a,c,d){if(!aria.utils.Json.isMetadata(a)){b[this.META_PREFIX+a]&&this.validateValue(b,a,c,d);this.validateModel(b[a],c,d)}},processMessages:function(b,
a,c,d){var e=aria.utils.Path,g=aria.utils.Json,h,j,k;if(c==null)c={};if(b==null)return c;for(var i=0,l=b.length;i<l;i++){var f=b[i];this._updateCounters(f,c);if(f.type==this.TYPE_ERROR){if(f.fieldRef&&!f.metaDataRef)try{h=e.parse(f.fieldRef);j=h.pop();k=e.resolve(h,a);if(this.utilsType.isContainer(k))f.metaDataRef=this._getMeta(k,j);else throw null;}catch(n){this.$logError(this.RESOLVE_FAIL,[f.fieldRef],a)}if(f.metaDataRef){var m=g.copy(f.metaDataRef.errorMessages);if(m==null)m=[f.localizedMessage];
else m.push(f.localizedMessage);g.setValue(f.metaDataRef,"errorMessages",m);g.setValue(f.metaDataRef,"error",true)}}f.subMessages&&this.processMessages(f.subMessages,a,c,false)}if(d!==false){a=c.listOfMessages;c.listOfMessages=a&&a.length>0?a.concat(b):b}return c}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Date.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.Date",$singleton:true,$dependencies:["aria.utils.String","aria.utils.Type","aria.utils.environment.Date"],$resources:{dateRes:"aria.resources.DateRes",res:"aria.utils.UtilsRes"},$constructor:function(){this._cutYear=((new Date).getFullYear()+10)%100;this._environment=aria.utils.environment.Date;var a=this.dateRes,c=aria.utils.String,b=this.res;this.firstDayOfWeek=a.firstDayOfWeek;var d=this._interpret_monthTexts=["JAN","FEB","MAR","APR","MAY","JUN","JUL",
"AUG","SEP","OCT","NOV","DEC"];this.formatPatterns={d:function(e,f){return c.pad(e.getDate(),f,"0",true)},M:function(e,f){switch(f){case 1:case 2:return c.pad(e.getMonth()+1,f,"0",true);case 3:return a.month[e.getMonth()].substring(0,f);default:return a.month[e.getMonth()]}},I:function(e){return d[e.getMonth()]},y:function(e,f){switch(f){case 1:case 2:return e.getFullYear().toString().slice(2);default:return c.pad(e.getFullYear(),f,"0",true)}},G:function(){return aria.utils.Date.NOT_SUPPORTED_MESSAGE},
E:function(e,f){switch(f){case 1:case 2:case 3:return a.day[e.getDay()].substring(0,f);default:return a.day[e.getDay()]}},h:function(e,f){var g=e.getHours();if(g===0)g=12;else if(g>=13)g-=12;if(g<10&&f===2)g="0"+g;return g},H:function(e,f){var g=e.getHours();if(g<10&&f===2)g="0"+g;return g},a:function(e){return e.getHours()<12?b.timeFormatLabels.am:b.timeFormatLabels.pm},m:function(e,f){var g=e.getMinutes();if(g<10&&f===2)g="0"+g;return g},s:function(e,f){var g=e.getSeconds();if(g<10&&f===2)g="0"+
g;return g}};this._formatCache={};this._interpret_isValid=/^[\d\W]*([a-z]{3})?[\d\W]*$/i;this._interpret_specialCase1=/^\d{1,2}$/;this._interpret_specialCase2=/^[+\-]\d{1,3}$/;this._interpret_specialCase3=/^(\d{1,2}[a-z]{3}\d{0,4})\/([+\-]\d{1,3})$/i;this._interpret_littleDate=/^\d\W\d$/;this._interpret_isMonth=/([a-z]{3})/i;this._interpret_digitOnly=/^\d+$/;this._separators=/[^\w]/;this._interpret_time_ampm=/am|pm|a\.m\.|p\.m\.|a|p|\sp\sm/g;this._interpret_time_isValid=/^\d/;this._interpret_time_remove_unwantedCharacters=
/[^\\h;m,.\-:/\d]+/gi;this._interpret_time_remove_separatorCharacters=/[\\h;m,.\-:/\s]/;this._formatToUpperCase=false},$destructor:function(){this._formatCache=null},$statics:{PATTERN_ERROR_MESSAGE:"##PATTERN_ERROR##",FORMAT_ERROR_MESSAGE:"##FORMAT_ERROR##",NOT_SUPPORTED_MESSAGE:"##NOT_SUPPORTED##",FORMATTER_STATEMENT_NOT_FOUND:"Following pattern %1 is not defined for this formatter: %2",FORMATTER_UNFINISHED_LITTERAL:"Unfinished litteral in this formatter: %1",INVALID_FORMAT_TYPE:"Application config format can only be a string or a function"},
$prototype:{interpretTime:function(a){var c;var b=c=0,d=0,e=0,f=0;if(!a)return null;if(!this._isValidTime(a))return null;if(this._isPM(a))e=12;a=this._removeAMPM(a);a=this._removeUnwantedCharacters(a);if(!this._isValidTime(a))return null;c=this._calculateHours(a);if(c===null)return null;for(f=0;f<c[1];f++)a=this._removeHMS(a);c=parseFloat(c);if(c<12)c+=e;if(c===24)c=0;a=this._removeSeparator(a);if(!this._isValidTime(a))return c=this._returnTime(c,b,d);b=this._calculateMS(a);for(f=0;f<b[1];f++)a=this._removeHMS(a);
b=parseFloat(b);a=this._removeSeparator(a);if(!this._isValidTime(a))return c=this._returnTime(c,b,d);d=parseFloat(this._calculateMS(a));return c=this._returnTime(c,b,d)},_isValidTime:function(a){return this._interpret_time_isValid.test(a)?true:false},_isPM:function(a){a=a.toLowerCase();a=a.match(this._interpret_time_ampm);return a!==null&&a[0].indexOf("p")!==-1?true:false},_removeAMPM:function(a){var c=a.toLowerCase();c=a.match(this._interpret_time_ampm);return a=a.replace(c,"")},_removeUnwantedCharacters:function(a){var c=
a.match(this._interpret_time_remove_unwantedCharacters);if(c!==null)for(var b=0;b<c.length;b++)if(a.indexOf(c[b])!==-1)a=a.replace(c[b],"");return a=aria.utils.String.trim(a)},_removeHMS:function(a){var c=a.match(this._interpret_time_isValid);return a=a.replace(c,"")},_removeSeparator:function(a){var c=a.match(this._interpret_time_remove_separatorCharacters);return a=a.replace(c,"")},_calculateHours:function(a){var c=[],b=a.charAt(0),d=a.charAt(1);a.charAt(2);if(b==="2"&&d==="4"){c[0]=0;c[1]=2;return c}if(d.match(this._interpret_digitOnly)&&
(b==="2"&&d<"4"||b<"2")){c[0]=b+d;c[1]=2;return c}else if(d.match(this._interpret_digitOnly)&&a.length>3)return null;else{c[0]=b;c[1]=1}return c[0].match(this._interpret_digitOnly)?c:null},_calculateMS:function(a){var c=[],b=a.charAt(0);a=a.charAt(1);if(a.match(this._interpret_digitOnly)&&b<6){c[0]=b+a;c[1]=2;return c}else{c[0]=b;c[1]=1}return c[0].match(this._interpret_digitOnly)?c:null},_returnTime:function(a,c,b){var d=new Date;d.setHours(a,c,b);return d},interpret:function(a,c){var b,d,e,f,g;
if(!a)return null;d=aria.utils.String.trim(a);if(!this._interpret_isValid.test(d))return null;if(this._interpret_specialCase1.test(d)){e=parseInt(d,10);b=new Date;b.setDate(e);if(b.getDate()!==e)return null;return b}if(this._interpret_specialCase2.test(d)){e=parseInt(d,10);if(Math.abs(e)>365)return null;b=c!=null?new Date(c.getTime()):new Date;b.setDate(b.getDate()+e);return b}if(this._interpret_specialCase3.test(d)){e=this._interpret_specialCase3.exec(d);f=e[1];e=parseInt(e[2],10);if(Math.abs(e)>
365)return null;(b=this.interpret(f))&&b.setDate(b.getDate()+e);return b}if(d.length<3)return null;if(d.length==3){if(this._interpret_isMonth.test(d)){for(e=0;e<12;e++)if(d===this._interpret_monthTexts[e]){b=new Date;if(b.getMonth()!=e){b.setDate(1);b.setMonth(e)}return b}return null}if(this._interpret_littleDate.test(d))d="0"+d;else return null}this.$assert("234",d.length>3);b=this._environment.getDateFormats().dateBeforeMonth;d=this._interpret_digitOnly.test(d)?d.slice(0,2)+"/"+d.slice(2,4)+"/"+
d.slice(4):d.replace(this._interpret_isMonth,"/$1/");d=d.split(/\W+/);for(var h=0,i=d.length;h<i;h++)d[h]||d.splice(h,1);if(d.length!=2&&d.length!=3)return null;if(d.length==2)if(this._interpret_isMonth.test(d[1])){e=d[0];f=d[1]}else if(b)if(this._interpret_isMonth.test(d[0])){e="1";f=d[0];g=d[1]}else{e=d[0];f=d[1]}else{f=d[0];if(d[1].length>2){e=d[1].slice(0,2);g=d[1].slice(2)}else e=d[1]}if(d.length==3){if(this._interpret_isMonth.test(d[1])){e=d[0];f=d[1]}else if(b){e=d[0];f=d[1]}else{e=d[1];f=
d[0]}g=d[2]}if(this._interpret_digitOnly.test(f))f=parseInt(f,10)-1;else{f=f.toUpperCase();for(b=0;b<12;b++)if(f===this._interpret_monthTexts[b]){f=b;break}if(!aria.utils.Type.isNumber(f))return null}if(this._interpret_digitOnly.test(e))e=parseInt(e,10);else return null;if(g){if(this._interpret_digitOnly.test(g))g=parseInt(g,10);else return null;if(g<100)g+=g>this._cutYear?1900:2E3;b=new Date(g,f,e);if(!(b.getDate()!=e||b.getMonth()!=f||b.getFullYear()!=g))return b}else{b=new Date;g=(new Date(b.getFullYear(),
b.getMonth(),b.getDate())).getTime();b=new Date(b.getFullYear(),f,e);if(b.getTime()<g)b=new Date(b.getFullYear()+1,f,e);if(!(b.getDate()!=e||b.getMonth()!=f))return b}return null},format:function(a,c,b){if(typeof c==="function")c=c();else typeof c!=="string"&&this.$logError(this.INVALID_FORMAT_TYPE);c=this._getFormatFunction(c);this.$assert(118,aria.utils.Type.isFunction(c));if(b)a=new Date(a.getUTCFullYear(),a.getUTCMonth(),a.getUTCDate(),a.getUTCHours(),a.getUTCMinutes(),a.getUTCSeconds(),a.getUTCMilliseconds());
return c(a)},_getFormatFunction:function(a){var c=a,b,d,e,f=[],g=false,h=0,i=[];if(this._formatCache[a])return this._formatCache[a];for(;c.length>0;){d=b;b=c.slice(0,1);c=c.slice(1);if(d!==b){this._pushIfExists(i,d,h,a);h=0}if(b==="'")if(e){if(d==="'")g||f.push("'");e=false}else{if(d==="'"){f.push("'");g=true}e=true}else{g=false;if(e)f.push(b);else if(this._separators.test(b))f.push(b);else{if(f.length){i.push(f.join(""));f=[]}if(b===d)h++;else h=1}}}e&&this.$logError(this.FORMATTER_UNFINISHED_LITTERAL,
a);this._pushIfExists(i,b,h,a);f.length&&i.push(f.join(""));var m=this._formatToUpperCase;this._formatToUpperCase=false;c=function(n){for(var k,j=[],l=0,o=i.length;l<o;l++){k=i[l];aria.utils.Type.isObject(k)?j.push(k.patternFn(n,k.occurency)):j.push(k)}j=j.join("");if(m)j=j.toUpperCase();return j};return this._formatCache[a]=c},_pushIfExists:function(a,c,b,d){var e,f=aria.utils.Type;if(b){if(c=="U")return this._formatToUpperCase=true;e=this.formatPatterns[c];if(f.isFunction(e))a.push({patternFn:e,
occurency:b});else{this.$logError(this.FORMATTER_STATEMENT_NOT_FOUND,[c,d]);a.push(aria.utils.Date.PATTERN_ERROR_MESSAGE)}}},isSameDay:function(a,c){if(!a||!c)return false;var b=this._getFormatFunction("ddMMyyyy");return b(a)===b(c)},getStartOfWeek:function(a,c){if(c==null)c=this.firstDayOfWeek;var b=new Date(a),d=a.getDay()-c;if(d<0)d+=7;b.setDate(b.getDate()-d);return b},dayDifference:function(a,c){var b=Date.UTC(a.getFullYear(),a.getMonth(),a.getDate());b=(Date.UTC(c.getFullYear(),c.getMonth(),
c.getDate())-b)/864E5;this.$assert(949,b==Math.round(b));return b},removeTime:function(a){if(a==null)return null;return a.getHours()!=0||a.getMinutes()!=0||a.getSeconds()!=0||a.getMilliseconds()!=0?new Date(a.getFullYear(),a.getMonth(),a.getDate()):a},dayOfWeekNbrSinceStartOfYear:function(a){var c=Date.UTC(a.getFullYear(),0,1);a=(Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())-c)/864E5;this.$assert(981,a==Math.round(a));return 1+Math.floor(a/7)}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Delegate.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.Delegate",$dependencies:["aria.utils.Event","aria.DomEvent","aria.utils.Store","aria.utils.IdManager","aria.utils.Callback","aria.utils.Array","aria.core.Browser"],$singleton:true,$events:{elementFocused:{description:"notifies that an element defined inside Aria Templates has received focus",properties:{focusedElement:"{HTMLElement} element that has received the focus"}},elementBlurred:{description:"notifies that an element defined inside Aria Templates has lost focus",
properties:{blurredElement:"{HTMLElement} element that has lost the focus"}}},$constructor:function(){this.depth=-1;this.delegatedOnBody=["click","focus","blur","focusin","focusout","mousedown","mouseup","mousemove","mouseover","mouseout","contextmenu"];this.delegatedOnWindow=["keydown","keyup","keypress"];this.rootListener=aria.core.Browser.isIE?document.body:window;aria.core.Browser.isIE||this.delegatedOnBody.push("change","paste","cut");this._delegatedMap={};var a,b;a=0;for(b=this.delegatedOnBody.length;a<
b;a++){var c=this.delegatedOnBody[a];this._delegatedMap[c]=true}a=0;for(b=this.delegatedOnWindow.length;a<b;a++){c=this.delegatedOnWindow[a];this._delegatedMap[c]=true}this.delegateExpando="atdelegate";this.__delegateMapping=null;this.stopper=document.body;this.__idMgr=new aria.utils.IdManager("d");this._focusTracking=this._changed=this.__stackCache=null},$destructor:function(){this.stopper=null;this.__idMgr.$dispose();this.__idMgr=null;if(this.__delegateMapping){var a=aria.utils.Event,b,c;b=0;for(c=
this.delegatedOnBody.length;b<c;b++)a.removeListener(document.body,this.delegatedOnBody[b],{fn:this.delegate});b=0;for(c=this.delegatedOnWindow.length;b<c;b++)a.removeListener(this.rootListener,this.delegatedOnWindow[b],{fn:this.delegate});this.__delegateMapping=null}this._focusTracking=this._delegatedMap=this.delegated=this.rootListener=this.rootListener=null},$statics:{DELEGATE_UTIL_CALLBACK_FAIL:"Error catch in callback for event %1"},$prototype:{isDelegated:function(a){return this._delegatedMap[a]},
add:function(a){this.cleanCache();if(!this.__delegateMapping){this.__delegateMapping={};var b=aria.utils.Event,c,d;c=0;for(d=this.delegatedOnBody.length;c<d;c++)b.addListener(document.body,this.delegatedOnBody[c],{fn:this.delegate,scope:this});c=0;for(d=this.delegatedOnWindow.length;c<d;c++)b.addListener(this.rootListener,this.delegatedOnWindow[c],{fn:this.delegate,scope:this})}b=this.__idMgr.getId();this.__delegateMapping[b]=new aria.utils.Callback(a);return b},getMarkup:function(a){return this.delegateExpando+
"='"+a+"'"},addExpando:function(a,b){a.setAttribute(this.delegateExpando,b)},getFallbackMarkup:function(a,b,c){this.getFallbackMarkup=aria.core.Browser.isIE?function(d,e,f){return" on"+d+"=\"aria.utils.Delegate.directCall(event, '"+e+"', "+(f?"true":"false")+', this)"'}:function(d,e,f){var g="directCall";if("mouseleave"==d||"mouseenter"==d){d="mouseleave"==d?"mouseout":"mouseover";g="mouseMovement"}return" on"+d+'="aria.utils.Delegate.'+g+"(event, '"+e+"', "+(f?"true":"false")+', this)"'};return this.getFallbackMarkup(a,
b,c)},__wrapEvent:function(a,b){return a.$DomEvent?a:b?new aria.templates.DomEventWrapper(a):new aria.DomEvent(a)},directCall:function(a,b,c){a=this.__wrapEvent(a,c);var d;if(b=this.__delegateMapping[b])d=b.call(a);a.$dispose();return d},mouseMovement:function(a,b,c,d){if(aria.utils.Dom.isAncestor(a.relatedTarget,d)===false){var e=this.__wrapEvent(a,c);e.type=a.type=="mouseover"?"mouseenter":"mouseleave";e.setTarget(d);return this.directCall(e,b,c,d)}},remove:function(a){this.cleanCache();if(this._changed)this._changed[a]=
true;this.__delegateMapping[a].$dispose();this.__delegateMapping[a]=null;this.__idMgr.releaseId(a)},delegate:function(a){if(!this.__stackCache)this.__stackCache={};var b=this.depth,c=[],d,e,f;a=this.__wrapEvent(a);f=a.target;for(var g=false;b&&f&&f!=this.stopper;){if(f.attributes)if(e=f.attributes[this.delegateExpando]){g=true;e=e.nodeValue;if(d=this.__stackCache[e]){c=c.concat(d);break}else c.push({expandoValue:e,target:f})}f=f.parentNode;b--}b=false;if(this._changed)b=true;else this._changed={};
d=0;for(var i=c.length;d<i;d++){f=c[d];e=f.expandoValue;f=f.target;if(d===0)this.__stackCache[e]=c;if(!this._changed[e]){e=this.__delegateMapping[e];a.delegateTarget=f;var h;if(e)try{h=e.call(a)}catch(j){this.$logError(this.DELEGATE_UTIL_CALLBACK_FAIL,[a.type],{event:a})}if(h===false||a.hasStopPropagation)break}}if(!b)this._changed=null;if(h!==false&&!a.hasStopPropagation&&aria.templates)(c=aria.templates.NavigationManager)&&c.handleGlobalNavigation(a);if(a.type=="focus")(this._focusTracking=a.target)&&
g&&this.$raiseEvent({name:"elementFocused",focusedElement:this._focusTracking});else if(a.type=="blur"){g&&this.$raiseEvent({name:"elementBlurred",blurredElement:this._focusTracking});this._focusTracking=null}a.$dispose()},cleanCache:function(){if(this.__stackCache){for(var a in this.__stackCache)if(this.__stackCache.hasOwnProperty(a)){for(var b=this.__stackCache[a],c=0,d=b.length;c<d;c++){b.target=null;b.expandoValue=null;delete b.target;delete b.expandoValue}delete this.__stackCache[c]}this.__stackCache=
null}},getFocus:function(){return this._focusTracking}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Dom.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.Dom",$dependencies:["aria.core.JsonValidator","aria.core.Browser"],$singleton:true,$constructor:function(){this._isCSS1Compat=document.compatMode=="CSS1Compat";this._documentScrollElement=null},$statics:{DIV_NOT_FOUND:"Missing div '%1' in DOM.",INSERT_ADJACENT_INVALID_POSITION:"Invalid position %1. Expected one of: beforeBegin, afterBegin, beforeEnd or afterEnd."},$prototype:{getElementById:function(a){this.getElementById=aria.core.Browser.isIE6||aria.core.Browser.isIE7?
function(d){var c=document.getElementById(d);if(c)if(c.getAttribute("id")==d)return c;else for(var b in document.all)if(b.id==d)return b;return null}:function(d){return document.getElementById(d)};return this.getElementById(a)},getNextSiblingElement:function(a,d){if(d==null)d=1;for(;a&&d>0;)(a=a.nextSibling)&&a.nodeType==1&&d--;return a},getPreviousSiblingElement:function(a,d){if(d==null)d=1;for(;a&&d>0;)(a=a.previousSibling)&&a.nodeType==1&&d--;return a},getDomElementChild:function(a,d,c){if(!a)return null;
a=a.childNodes;for(var b=0,e=a.length,f=c?e-1:0;c?f>=0:f<e;c?f--:f++)if(a[f].nodeType==1){if(b==d)return a[f];b++}return null},getDomElementsChildByTagName:function(a,d){if(!a)return null;return a.getElementsByTagName(d)},getDomElementChildReverse:function(a,d){return this.getDomElementChild(a,d,true)},refreshDomElt:function(a){this.refreshDomElt=aria.core.Browser.isIE7?function(d){try{d.parentNode.style.cssText+="";d.parentNode.style.zoom=1}catch(c){}}:aria.core.Browser.isIE8?function(){for(var d=
0,c=Aria.rootTemplates.length;d<c;d++){var b=Aria.rootTemplates[d];if(b._cfg&&b._cfg.tplDiv){b=b._cfg.tplDiv;b.className=b.className}}}:function(){};this.refreshDomElt(a)},replaceHTML:function(a,d){var c=a;if(typeof c=="string")c=this.getElementById(c);if(c){try{c.innerHTML="";c.innerHTML=d}catch(b){var e=this._createTableElement(c.tagName,d);if(e){this.replaceDomElement(c,e);this.copyAttributes(c,e);c=e}else throw b;}aria.utils&&aria.utils.Delegate&&aria.utils.Delegate.delegate(aria.DomEvent.getFakeEvent("contentchange",
c))}else{this.$logError(this.DIV_NOT_FOUND,[a]);return null}return c},_createTableElement:function(a,d){a=a.toUpperCase();var c=document.createElement("DIV");if(a=="TBODY"||a=="THEAD"||a=="TFOOT"){c.innerHTML=["<TABLE><",a,">",d,"</",a,"></TABLE>"].join("");c=c.children[0].children[0]}else if(a=="TR"){c.innerHTML=["<TABLE><TBODY><",a,">",d,"</",a,"></TBODY></TABLE>"].join("");c=c.children[0].children[0].children[0]}else{c.innerHTML=["<",a,">",d,"</",a,">"].join("");c=c.children[0]}this.$assert(194,
!c||c.tagName.toUpperCase()==a);return c},replaceDomElement:function(a,d){var c=a.parentNode;c.insertBefore(d,a);c.removeChild(a)},insertAdjacentHTML:function(a,d,c){this.insertAdjacentHTML=document.body.insertAdjacentHTML?function(b,e,f){try{b.insertAdjacentHTML(e,f)}catch(h){var i;if(e=="afterBegin"||e=="beforeEnd")i=b;else if(e=="beforeBegin"||e=="afterEnd")i=b.parentNode;else{this.$logError(this.INSERT_ADJACENT_INVALID_POSITION,[e]);return}if(f=this._createTableElement(i.tagName,f)){var j=f.lastChild;
if(j){this.insertAdjacentElement(b,e,j);for(b=f.lastChild;b;){i.insertBefore(b,j);j=b;b=f.lastChild}}}else throw h;}}:function(b,e,f){var h=document.createRange();e=="beforeBegin"||e=="afterEnd"?h.selectNode(b):h.selectNodeContents(b);f=h.createContextualFragment(f);this.insertAdjacentElement(b,e,f);h.detach()};this.insertAdjacentHTML(a,d,c)},insertAdjacentElement:function(a,d,c){this.insertAdjacentElement=document.body.insertAdjacentElement?function(b,e,f){b.insertAdjacentElement(e,f)}:function(b,
e,f){if(e=="beforeBegin")b.parentNode.insertBefore(f,b);else if(e=="afterBegin")b.insertBefore(f,b.firstChild);else if(e=="beforeEnd")b.appendChild(f);else e=="afterEnd"?b.parentNode.insertBefore(f,b.nextSibling):this.$logError(this.INSERT_ADJACENT_INVALID_POSITION,[e])};this.insertAdjacentElement(a,d,c)},copyAttributes:function(a,d){this.copyAttributes=document.body.mergeAttributes?function(c,b){b.mergeAttributes(c,false)}:function(c,b){for(var e=c.attributes,f=0,h=e.length;f<h;f++){var i=e[f];b.setAttribute(i.name,
i.value)}};this.copyAttributes(a,d)},_getViewportSize:function(){var a=document.documentElement;return{width:a.clientWidth,height:a.clientHeight}},_getDocumentScroll:function(a){var d=0,c=0,b=this.getDocumentScrollElement();if(a!=null){for(;a!=null;){if(a.scrollLeft)d+=a.scrollLeft;if(a.scrollTop)c+=a.scrollTop;a=a.parentNode}d-=b.scrollLeft;c-=b.scrollTop}else{d=b.scrollLeft;c=b.scrollTop}if(b!=document.body){d+=document.body.scrollLeft;c+=document.body.scrollTop}return{scrollLeft:d,scrollTop:c}},
getFullPageSize:function(){var a=!this._isCSS1Compat||aria.core.Browser.isSafari||aria.core.Browser.isChrome?document.body:document.documentElement;a={width:a.scrollWidth,height:a.scrollHeight};var d=this._getViewportSize();return{width:Math.max(a.width,d.width),height:Math.max(a.height,d.height)}},calculatePosition:function(a,d){if(a){var c=aria.core.Browser,b=0,e=0,f=0,h=0,i=true,j=0,g=a,k;if(g.getBoundingClientRect&&!d){j=c.isIE6||c.isIE7?2:0;try{k=g.getBoundingClientRect();i=false;b=k.left-j;
e=k.top-j}catch(l){e=b=0}}else for(;g&&g.parentNode;){b+=g.offsetLeft;e+=g.offsetTop;k=aria.utils.Dom.getStyle(g,"position");if(d&&j>0&&k=="absolute")break;g=g.offsetParent;j++}j=0;for(g=a;g&&g.parentNode&&g.parentNode!=document.body&&g.parentNode.tagName;){if(!c.isOpera&&g.nodeName!="HTML")if(g.scrollTop!==0&&g.scrollTop){f=g.scrollTop;if(i)e-=g.scrollTop}else{if(g.scrollLeft!==0&&g.scrollLeft){h=g.scrollLeft;if(i)b-=g.scrollLeft}}else if(c.isOpera)if(g.scrollTop!==0&&g.scrollTop!=g.offsetTop){if(i)e-=
g.scrollTop;f=g.scrollTop}else if(g.scrollLeft!==0&&g.scrollLeft!=g.offsetLeft){h=g.scrollLeft;if(i)b-=g.scrollLeft}k=aria.utils.Dom.getStyle(g,"position");if(j>0&&k=="absolute")break;j++;g=g.parentNode}return{top:e,left:b,scrollTop:f,scrollLeft:h}}},getClientGeometry:function(a){var d=this.calculatePosition(a);return{x:d.left+a.clientLeft,y:d.top+a.clientTop,width:a.clientWidth,height:a.clientHeight}},getGeometry:function(a){if(!a)return null;var d,c;d=aria.core.Browser;var b=this.calculatePosition(a);
if(a===document.body){b=this.getFullPageSize();return{x:0,y:0,width:b.width,height:b.height}}else{if(d.isChrome||d.isSafari){c=a.getBoundingClientRect();d=c.width;c=c.height}else{d=a.offsetWidth;c=a.offsetHeight}b={x:b.left,y:b.top,width:d,height:c};a=a.parentNode;d=document.documentElement;for(c=document.body;a&&a!=d&&a!=c;){var e=this.getClientGeometry(a),f=this.getStyle(a,"overflowX"),h=this.getStyle(a,"overflowY");if(f=="auto"||f=="scroll"){f=e.x-b.x;if(f>0){b.x+=f;b.width-=f;if(b.width<0)return null}f=
b.x+b.width-e.x-e.width;if(f>0){b.width-=f;if(b.width<0)return null}}if(h=="auto"||h=="scroll"){f=e.y-b.y;if(f>0){b.y+=f;b.height-=f;if(b.height<0)return null}f=b.y+b.height-e.y-e.height;if(f>0){b.height-=f;if(b.height<0)return null}}a=a.parentNode}return b}},getStyle:function(a,d){this.getStyle=aria.core.Browser.isIE?function(c,b){if(b=="opacity"){var e=100;try{e=c.filters["DXImageTransform.Microsoft.Alpha"].opacity}catch(f){try{e=c.filters("alpha").opacity}catch(h){}}return e/100}else if(b=="float")b=
"styleFloat";e=c.currentStyle?c.currentStyle[b]:null;return c.style[b]||e}:function(c,b){var e=null;if(b=="float")b="cssFloat";var f=window.getComputedStyle(c,"");if(f)e=f[b];return c.style!==null?c.style[b]||e:e};return this.getStyle(a,d)},centerInViewport:function(a,d){var c=this._getViewportSize(),b=this._getDocumentScroll(d);return{left:b.scrollLeft+(c.width-a.width)/2,top:b.scrollTop+(c.height-a.height)/2}},isInViewport:function(a,d,c){var b=this._getViewportSize();c=this._getDocumentScroll(c);
return a.top<c.scrollTop||a.left<c.scrollLeft||a.top+d.height>c.scrollTop+b.height||a.left+d.width>c.scrollLeft+b.width?false:true},fitInViewport:function(a,d,c){var b=this._getViewportSize(),e=this._getDocumentScroll(c);c=aria.utils.Math.normalize(a.top,e.scrollTop,e.scrollTop+b.height-d.height);a=aria.utils.Math.normalize(a.left,e.scrollLeft,e.scrollLeft+b.width-d.width);return{top:c,left:a}},isAncestor:function(a,d){for(var c=document.body,b=a;b&&b!=c;){if(b==d)return true;b=b.parentNode}return b==
d},isInDom:function(a){return this.isAncestor(a,document.body)},removeElement:function(a){a.parentNode&&a.parentNode.removeChild(a)},scrollIntoView:function(a,d){for(var c=a,b=c.getBoundingClientRect(),e=false,f=this.getDocumentScrollElement();a;)if(a=a==document.body?f:a.parentNode){var h;h=a==f?{left:0,top:0}:a.getBoundingClientRect();var i=b.left-(h.left+(parseInt(a.style.borderLeftWidth,10)|0)),j=b.right-(h.left+a.clientWidth+(parseInt(a.style.borderLeftWidth,10)|0)),g=b.top-(h.top+(parseInt(a.style.borderTopWidth,
10)|0));h=b.bottom-(h.top+a.clientHeight+(parseInt(a.style.borderTopWidth,10)|0));if(i<0)a.scrollLeft+=i;else if(j>0)a.scrollLeft+=j;if(d===true&&!e)a.scrollTop+=g;else if(d===false&&!e)a.scrollTop+=h;else if(g<0)a.scrollTop+=g;else if(h>0)a.scrollTop+=h;if(a==f)a=null;else{i=c.getBoundingClientRect();if(i.top!=b.top)e=true;b=i}}},getDocumentScrollElement:function(){if(!this._documentScrollElement)this._documentScrollElement=!(aria.core.Browser.isSafari||aria.core.Browser.isChrome)&&this._isCSS1Compat?
document.documentElement:document.body;return this._documentScrollElement}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/DomBeans.js
//MJhO76UFv6
Aria.beanDefinitions({$package:"aria.utils.DomBeans",$description:"",$namespaces:{json:"aria.core.JsonTypes"},$beans:{Size:{$type:"json:Object",$description:"Object description for the size of bi-dimensional object",$properties:{width:{$type:"json:Integer",$description:"Width value of the Size object",$default:0},height:{$type:"json:Integer",$description:"Height value of the Size object",$default:0}}},Position:{$type:"json:Object",$description:"Object description for the position of bi-dimensional object",
$properties:{top:{$type:"json:Integer",$description:"Top value of the Position object",$default:0},left:{$type:"json:Integer",$description:"Left value of the Position object",$default:0},scrollTop:{$type:"json:Integer",$description:"The total scrolling offset (Top)",$default:0},scrollLeft:{$type:"json:Integer",$description:"The total scrolling offset (Left)",$default:0}}}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/DomOverlay.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.DomOverlay",$dependencies:["aria.utils.overlay.LoadingOverlay","aria.utils.Type","aria.utils.Event"],$singleton:true,$statics:{UNIQUE_ID_GENERATOR:12},$constructor:function(){this.overlays={};this.bodyOverlay=null;aria.utils.Event.addListener(window,"scroll",{fn:this.__onScroll,scope:this},true)},$destructor:function(){aria.utils.Event.removeListener(window,"scroll",{fn:this.__onScroll})},$prototype:{create:function(b,a){var c=this.__getOverlay(b);if(c){c.overlay.refresh();
return c.id}var d=++this.UNIQUE_ID_GENERATOR;c=new aria.utils.overlay.LoadingOverlay(b,d,a);if(b!==document.body){this.overlays[d]=c;b.__overlay=d}else this.bodyOverlay=c;return d},detachFrom:function(b){var a=this.__getOverlay(b);if(a){a.overlay.$dispose();a=a.id;if(b===document.body)this.bodyOverlay=null;else delete this.overlays[a];return a}},__getOverlay:function(b){if(b===document.body)return!this.bodyOverlay?null:{overlay:this.bodyOverlay};else{var a=b.__overlay;if(a){var c=this.overlays[a];
if(c)return{overlay:c,id:a};else b.__overlay=null}}},__onScroll:function(){var b=this.overlays,a;for(a in b)b.hasOwnProperty(a)&&b[a].refreshPosition()},disposeOverlays:function(b){if(aria.utils.Type.isArray(b))for(var a=0,c=b.length;a<c;a+=1){var d=this.overlays[b[a]];if(d){d.$dispose();delete this.overlays[b[a]]}}}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Ellipsis.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.Ellipsis",$dependencies:["aria.utils.Function","aria.utils.FireDomEvent","aria.utils.Dom","aria.popups.Popup"],$constructor:function(a,b,d,e,f){this.textContent=a.innerHTML;this.context=f;this.ellipsisElement=a;this.ellipsesNeeded=false;if(a.childNodes.length==1&&a.childNodes[0].nodeType==3){if(!b){b=a.parentNode.offsetWidth;if(a.parentNode.lastChild.className=="xICNsortIndicator")if(a.parentNode.lastChild.offsetWidth>0)b-=a.parentNode.lastChild.offsetWidth}var c=
this._createSizerEl(a);c.innerHTML=a.innerHTML;document.body.appendChild(c);var g=c.offsetWidth;c.parentNode.removeChild(c);c.innerHTML=e+"&nbsp;";document.body.appendChild(c);f=c.offsetWidth;c.parentNode.removeChild(c);if(g>b){this.ellipsesNeeded=true;c=document.createElement("SPAN");c.style.whiteSpace="nowrap";c.style.overflow="hidden";c.style.display="inline-block";c.style.verticalAlign="bottom";if(aria.core.Browser.isIE6)b-=4;b-=f;if(b<0)b=0;c.style.width=b+"px";if(d=="left")c.style.direction=
"rtl";c.innerHTML=a.innerHTML;a.innerHTML="";b=document.createElement("SPAN");if(d=="left"){b.innerHTML=e+"&nbsp;";a.appendChild(b);a.appendChild(c)}else if(d=="right"){b.innerHTML="&nbsp;"+e;a.appendChild(c);a.appendChild(b)}}}else this.$logWarn(this.ELLIPSIS_NONTEXTUAL_ELEMENTS)},$destructor:function(){if(this._popup&&this._popup!==null){this._popup.close();this._popup=null}this.ellipsesNeeded=this.ellipsisElement=this.textContent=this.context=null;this.callbackID&&aria.core.Timer.cancelCallback(this.callbackID);
this.callbackID=null},$statics:{ELLIPSIS_NONTEXTUAL_ELEMENTS:"Non-textual elements cannot be constrained to a specific width"},$prototype:{_createSizerEl:function(a){var b=document.createElement(a.tagName);b.className=a.className;b.setAttribute("style",a.getAttribute("style"));a.parentNode.appendChild(b);b.style.visibility="hidden";b.style.position="absolute";b.style.whiteSpace="nowrap";return b},_renderFullText:function(a){a.write("<span style='cursor:pointer;white-space:nowrap;background:white;font-weight:bold;'>"+
this.textContent+"</span>")},displayFullText:function(a){if(this.callbackID){aria.core.Timer.cancelCallback(this.callbackID);this.callbackID=null}if(this._popup==null&&this.ellipsesNeeded===true)this.callbackID=aria.core.Timer.addCallback({fn:this._showPopup,scope:this,delay:500,args:a})},_showPopup:function(a){var b=this.context.createSection({fn:this._renderFullText,scope:this}),d=new aria.popups.Popup;this._popup=d;d.$on({scope:this,onAfterClose:this._onAfterPopupClose});d.open({section:b,domReference:this.ellipsisElement,
preferredPositions:[{reference:"top left",popup:"top left"}],closeOnMouseOut:true,offset:{top:a.top,left:a.left}});d.domElement.firstChild.onclick=aria.utils.Function.bind(this._popup_onmouseclick,this);this.callbackID=null},_popup_onmouseclick:function(){aria.utils.FireDomEvent.fireEvent("click",this.ellipsisElement,{})},_hideFullText:function(a){this.callbackID&&aria.core.Timer.cancelCallback(this.callbackID);if(this._popup!=null)aria.utils.Dom.isAncestor(a,this._popup.domElement)||this._popup&&
this._popup.closeOnMouseOut();this.callbackID=null},_onAfterPopupClose:function(){this._popup.$dispose();this._popup=null}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Event.js
//MJhO76UFv6
(function(){var i=[],j=[];Aria.classDefinition({$classpath:"aria.utils.Event",$dependencies:["aria.utils.Type","aria.utils.Callback","aria.core.Browser"],$singleton:true,$statics:{DEPRECATED_METHOD_MSG:"Warning!! addListener(element,event,callback,scope,args,useCapture) is deprecated, Please use addListener(element,event,aria.utils.Callback|json object,useCapture)",INVALID_TARGET:"Unable to add '%2' event on element %1"},$constructor:function(){this.typesUtil=aria.utils.Type;this.UA=aria.core.Browser;
this.isIE=this.UA.ie;var a=this;this._unload=function(b){a._unloadEvent(b)};this._simpleAdd(window,"unload",this._unload)},$destructor:function(){var a;j=null;for(var b=i.length-1;b>=0;b--)(a=i[b])&&this.removeListener(a[0],a[1],a[2],b);this._simpleRemove(window,"unload",this._unload);this._unload=null},$prototype:{_unloadEvent:function(a){for(var b=0,d=j.length;b<d;++b){var c=j[b];if(c){this.typesUtil.isObject(c[2])&&!c[2].$Callback?this.$callback(c[2]):c[2].call(this.getEvent(a));j[b]=null}}},addListener:function(a,
b,d,c,e,f){if(!d)return false;if("mousewheel"==b)if(this.UA.isIE){if(a==window)a=window.document}else this.UA.isOpera||this.UA.isSafari||(b="DOMMouseScroll");this.typesUtil.isFunction(d)||(f=c);f=(b=="focusin"||b=="focusout")&&!this.UA.ie?true:f;return this._addListener(a,this._getType(b),d,c,e,f)},_simpleAdd:function(){return window.addEventListener?function(a,b,d,c){a.addEventListener(b,d,c)}:window.attachEvent?function(a,b,d){a.attachEvent("on"+b,d)}:function(){}}(),_addListener:function(a,b,d,
c,e,f){if(this._isValidCollection(a)){for(var g=true,h=0,l=a.length;h<l;++h)g=this._addListener(a[h],b,d,c,e,f)&&g;return g}if(this.typesUtil.isString(a)){g=this.getElement(a);if(!g){this.$logError(this.INVALID_TARGET,[a,b]);a=g;return false}a=g}if(!this.typesUtil.isHTMLElement(a))return false;g=d;h=a;if(this.typesUtil.isFunction(d)){if(c)h=c===true?e:c;g={fn:d,scope:h,args:e};this.$logWarn(this.DEPRECATED_METHOD_MSG)}if(!d.$Callback){if(!g.fn||!this.typesUtil.isFunction(g.fn))return false;if(!g.scope)g.scope=
a}var k=d;d.$Callback||(k=new aria.utils.Callback(g));if("unload"==b&&e!==this){j[j.length]=[a,b,d];return true}c=function(m){return k.call(aria.utils.Event.getEvent(m,a))};i[i.length]=[a,b,d,c,f,k];try{this._simpleAdd(a,b,c,f)}catch(n){this.$logError(this.INVALID_TARGET,[a,b],n);this.removeListener(a,b,d);return false}return true},_isValidCollection:function(a){try{return a&&typeof a!=="string"&&a.length&&!a.tagName&&!a.alert&&typeof a[0]!=="undefined"}catch(b){return false}},getEvent:function(a){a=
a||window.event;if(!a)for(var b=this.getEvent.caller;b;){if((a=b.arguments[0])&&Event==a.constructor)break;b=b.caller}return a},_getType:function(a){return this._specialTypes[a]||a},_specialTypes:{focusin:aria.core.Browser.isIE?"focusin":"focus",focusout:aria.core.Browser.isIE?"focusout":"blur"},removeListener:function(a,b,d,c){var e;if("mousewheel"==b)if(this.UA.isIE){if(a==window)a=window.document}else this.UA.isOpera||this.UA.isSafari||(b="DOMMouseScroll");b=this._getType(b);if(this.typesUtil.isString(a)){a=
this.getElement(a);if(!a)return false}else if(this._isValidCollection(a)){c=true;for(e=a.length-1;e>-1;e--)c=this.removeListener(a[e],b,d)&&c;return c}if(!d||!(d.call||d.fn))return this.purgeElement(a,false,b);if("unload"==b){for(e=j.length-1;e>-1;e--){c=j[e];var f;f=c&&aria.utils.Type.isObject(c[2])&&!c[2].$Callback?"fn"in d&&c[2].fn==d.fn:c[2]==d;if(c&&c[0]==a&&c[1]==b&&f){j.splice(e,1);return true}}return false}e=null;if("undefined"===typeof c)c=this._getCacheIndex(i,a,b,d);if(c>=0)e=i[c];if(!a||
!e)return false;d=e[4]===true?true:false;try{this._simpleRemove(a,b,e[3],d)}catch(g){return false}delete i[c][3];i[c][2]!=i[c][5]&&i[c][5].$dispose();i.splice(c,1);return true},getElement:function(a){return typeof a==="string"?document.getElementById(a):a},_getCacheIndex:function(a,b,d,c){for(var e,f=0,g=a.length;f<g;f+=1){var h=a[f];e=h&&this.typesUtil.isObject(h[2])&&!h[2].$Callback?"fn"in c&&h[2].fn==c.fn:h[2]==c;if(h&&e&&h[0]==b&&h[1]==d)return f}return-1},_simpleRemove:function(){return window.removeEventListener?
function(a,b,d,c){a.removeEventListener(b,d,c)}:window.detachEvent?function(a,b,d){a.detachEvent("on"+b,d)}:function(){}}(),purgeElement:function(a,b,d){a=this.typesUtil.isString(a)?this.getElement(a):a;var c=this.getListeners(a,d),e;if(c)for(e=c.length-1;e>-1;e--){var f=c[e];this.removeListener(a,f.type,f.fn)}if(b&&a&&a.childNodes){e=0;for(c=a.childNodes.length;e<c;++e)this.purgeElement(a.childNodes[e],b,d)}},getListeners:function(a,b){var d=[],c;if(b)if(b==="unload")c=[j];else{b=this._getType(b);
c=[i]}else c=[i,j];for(var e=this.typesUtil.isString(a)?this.getElement(a):a,f=0;f<c.length;f+=1){var g=c[f];if(g)for(var h=0,l=g.length;h<l;++h){var k=g[h];if(k&&k[0]===e&&(!b||b===k[1]))d.push({type:k[1],fn:k[2],index:h})}}return d.length?d:null}}})})();
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/filters/DisplayXmlResponse.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.filters.DisplayXmlResponse",$extends:"aria.core.IOFilter",$constructor:function(){this.$IOFilter.constructor.call(this)},$prototype:{onResponse:function(a){var b=a.res;if(b.responseXML)if(b=this._xml2str(b.responseXML)){this.$logInfo("Request to the following URL produced the following result: "+a.url);this.$logInfo(b)}},_xml2str:function(a){try{return(new XMLSerializer).serializeToString(a)}catch(b){try{return a.xml}catch(c){this.$logWarn("Xmlserializer not supported")}}return false}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/FireDomEvent.js
//MJhO76UFv6
(function(){var c,u={click:1,dblclick:1,mouseover:1,mouseout:1,mousedown:1,mouseup:1,mousemove:1},w={keydown:1,keyup:1,keypress:1},v={focus:1,blur:1,change:1},h=function(g){typeof window.console!="undefined"&&typeof window.console.log!="undefined"&&window.console.log(g)},t=function(g,d,a){a=a||{};if(u[d]){var f=a.bubbles,i=a.cancelable,j=a.view,k=a.detail,l=a.screenX,m=a.screenY,n=a.clientX,o=a.clientY,e=a.ctrlKey,p=a.altKey,q=a.shiftKey,r=a.metaKey,s=a.button;a=a.relatedTarget;g||h("simulateMouseEvent(): Invalid target.");
if(c.isString(d)){d=d.toLowerCase();u[d]||h("simulateMouseEvent(): Event type '"+d+"' not supported.")}else h("simulateMouseEvent(): Event type must be a string.");c.isBoolean(f)||(f=true);c.isBoolean(i)||(i=d!="mousemove");c.isObject(j)||(j=window);c.isNumber(k)||(k=1);c.isNumber(l)||(l=0);c.isNumber(m)||(m=0);c.isNumber(n)||(n=0);c.isNumber(o)||(o=0);c.isBoolean(e)||(e=false);c.isBoolean(p)||(p=false);c.isBoolean(q)||(q=false);c.isBoolean(r)||(r=false);c.isNumber(s)||(s=0);var b=null;if(c.isFunction(document.createEvent)){b=
document.createEvent("MouseEvents");if(b.initMouseEvent)b.initMouseEvent(d,f,i,j,k,l,m,n,o,e,p,q,r,s,a||null);else{b=document.createEvent("UIEvents");b.initEvent(d,f,i);b.view=j;b.detail=k;b.screenX=l;b.screenY=m;b.clientX=n;b.clientY=o;b.ctrlKey=e;b.altKey=p;b.metaKey=r;b.shiftKey=q;b.button=s;b.relatedTarget=a}if(a&&!b.relatedTarget)if(d=="mouseout")b.toElement=a;else if(d=="mouseover")b.fromElement=a;g.dispatchEvent(b)}else if(c.isObject(document.createEventObject)){b=document.createEventObject();
b.bubbles=f;b.cancelable=i;b.view=j;b.detail=k;b.screenX=l;b.screenY=m;b.clientX=n;b.clientY=o;b.ctrlKey=e;b.altKey=p;b.metaKey=r;b.shiftKey=q;switch(s){case 0:b.button=1;break;case 1:b.button=4;break;case 2:break;default:b.button=0}b.relatedTarget=a;if(g.checked!=undefined)g.checked=!g.checked;g.fireEvent("on"+d,b)}else h("simulateMouseEvent(): No event simulation framework present.")}else if(w[d]){f=a.bubbles;i=a.cancelable;j=a.view;k=a.ctrlKey;l=a.altKey;m=a.shiftKey;n=a.metaKey;o=a.keyCode;a=
a.charCode;g||h("simulateKeyEvent(): Invalid target.");if(c.isString(d)){d=d.toLowerCase();switch(d){case "textevent":d="keypress";break;case "keyup":case "keydown":case "keypress":break;default:h("simulateKeyEvent(): Event type '"+d+"' not supported.")}}else h("simulateKeyEvent(): Event type must be a string.");c.isBoolean(f)||(f=true);c.isBoolean(i)||(i=true);c.isObject(j)||(j=window);c.isBoolean(k)||(k=false);c.isBoolean(l)||(l=false);c.isBoolean(m)||(m=false);c.isBoolean(n)||(n=false);c.isNumber(o)||
(o=0);c.isNumber(a)||(a=0);e=null;if(c.isFunction(document.createEvent)){try{e=document.createEvent("KeyEvents");e.initKeyEvent(d,f,i,j,k,l,m,n,o,a)}catch(x){try{e=document.createEvent("Events")}catch(y){e=document.createEvent("UIEvents")}finally{e.initEvent(d,f,i);e.view=j;e.altKey=l;e.ctrlKey=k;e.shiftKey=m;e.metaKey=n;e.keyCode=o;e.charCode=a}}g.dispatchEvent(e)}else if(c.isObject(document.createEventObject)){e=document.createEventObject();e.bubbles=f;e.cancelable=i;e.view=j;e.ctrlKey=k;e.altKey=
l;e.shiftKey=m;e.metaKey=n;e.keyCode=a>0?a:o;g.fireEvent("on"+d,e)}else h("simulateKeyEvent(): No event simulation framework present.")}else if(v[d]){a=d;g||h("simulateHtmlEvent(): Invalid target.");if(c.isString(a)){a=a.toLowerCase();v[a]||h("simulateHtmlEvent(): Event type '"+a+"' not supported.")}else h("simulateHtmlEvent(): Event type must be a string.");d=a==="change";f=null;if(c.isFunction(document.createEvent)){f=document.createEvent("HTMLEvents");f.initEvent(a,d,false);g.dispatchEvent(f)}else if(c.isObject(document.createEventObject)){f=
document.createEventObject();f.bubbles=d;f.cancelable=false;g.fireEvent("on"+a,f)}else h("simulateHtmlEvent(): No event simulation framework present.")}else h("simulate(): Event '"+d+"' can't be simulated.")};Aria.classDefinition({$classpath:"aria.utils.FireDomEvent",$singleton:true,$dependencies:["aria.utils.Type","aria.core.Browser"],$onload:function(){c=aria.utils.Type},$onunload:function(){c=null},$prototype:{fireEvent:function(g,d,a){t(d,g,a)},fireKeydownEventAdaptedForKeyNav:function(g,d){this.fireKeydownEventAdaptedForKeyNav=
aria.core.Browser.isIE||aria.core.Browser.isSafari?function(a,f){t(a,"keydown",f)}:function(a,f){t(a,"keydown",f);t(a,"keypress",f)};this.fireKeydownEventAdaptedForKeyNav(g,d)}}})})();
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/FormatFactory.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.FormatFactory",$dependencies:["aria.utils.Type"],$constructor:function(){this._statements={};this._statementsRegExp=/^\${[^}]*}/;this._formatFnCache={}},$destructor:function(){this._formatFnCache=this._statements=null},$statics:{PATTERN_ERROR_MESSAGE:"##PATTERN_ERROR##",FORMAT_ERROR_MESSAGE:"##FORMAT_ERROR##",FORMATTER_STATEMENT_NOT_FOUND:"Following pattern %1 is not defined for this formatter: %2"},$prototype:{setStatements:function(b){this._statements=
b},getFormatFunction:function(b){var d=[],a="",j,g,e="",c=b;if(this._formatFnCache[b])return this._formatFnCache[b];for(;c.length>0;){if(a=c.match(this._statementsRegExp)){if(e){d.push(e);e=""}a=a[0];g=a.slice(2,a.length-1);if(j=this._statements[g])d.push(j);else{this.$logError(this.FORMATTER_STATEMENT_NOT_FOUND,[g,b]);d.push(aria.utils.FormatFactory.PATTERN_ERROR_MESSAGE)}}if(a)c=c.slice(a.length);else{e+=c.charAt(0);c=c.slice(1)}}e&&d.push(e);a=function(k){var f,h="";try{for(var i=0,l=d.length;i<
l;i++){f=d[i];h+=aria.utils.Type.isFunction(f)?f(k):f}}catch(m){h=aria.utils.FormatFactory.FORMAT_ERROR_MESSAGE}return h};return this._formatFnCache[b]=a}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Function.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.Function",$singleton:true,$prototype:{bind:function(a,f){for(var d=[],b=2;b<arguments.length;b++)d.push(arguments[b]);return function(){for(var c=d.slice(0),e=0;e<arguments.length;e++)c.push(arguments[e]);return a.apply(f,c)}},wrapObjectFn:function(a,f,d,b){b||(b="");for(var c=0,e=d.length;c<e;c++){var g=d[c];f[b+g]=this.bind(a[g],a)}},bindCallback:function(a){a=this.$normCallback(a);return function(){a.fn.call(a.scope,arguments,a.args)}}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/HashManager.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.HashManager",$singleton:true,$dependencies:["aria.core.Browser","aria.utils.Type","aria.utils.Event","aria.utils.Object"],$statics:{INVALID_SETHASH_ARGUMENT:"Invalid argument passed to aria.utils.HashManager.setHash method.",INVALID_SETSEPARATORS_ARGUMENTS:"Invalid argument passed to aria.utils.HashManager.setSeparators method.",INVALID_SEPARATOR:"Expression %1 cannot be used as separator.",INVALID_HASHPOLLING_TRIGGER:"Enabling hash polling is allowed only in IE7.",
INVALID_HASHOBJECT_TYPE:"Invalid hash object: value corresponding to key %1 is not a string.",INVALID_HASHOBJECT_VALUE:"Invalid hash object: value '%1' corresponding to key '%2' of the hashObject contains one the non encodable separators '%3'",INVALID_HASHOBJECT_KEY:"Invalid hash object: key '%1' of the hashObject contains one the non encodable separators '%2'"},$constructor:function(){this._separators=[",","&"];this._separatorRegExp=this.__buildRegExpFromArray(this._separators);this._nonEncodableSeparators=
this.__getNonEncodedSeparators(this._separators);this._nonEncodableSepRegExp=this.__buildRegExpFromArray(this._nonEncodableSeparators);this._hashChangeCallbacks=[];this.__location=window.location;this._currentHashString=decodeURIComponent(this.getHashString());this._enableIE7polling=aria.core.Browser.isIE7;this._addHashChangeInternalCallback();this._typeUtil=aria.utils.Type;this.ie7PollDelay=75},$destructor:function(){this._removeHashChangeInternalCallback()},$prototype:{getHashObject:function(){return aria.utils.Json.copy(this._extractHashObject(this.getHashString()))},
getHashString:function(){var a=this.__location.href,b=a.indexOf("#");if(b!=-1)return a.substring(b+1);return""},setHash:function(a){var b="";if(this._typeUtil.isObject(a))if(this._validateHashObject(a))b=this._stringifyHashObject(a);else return;else if(this._typeUtil.isString(a))b=!a?"":a;else this.$logError(this.INVALID_SETHASH_ARGUMENT);if(this.getHashString()!=b)this.__location.hash=b},addCallback:function(a){this._hashChangeCallbacks.push(a)},removeCallback:function(a){for(var b=this._hashChangeCallbacks,
c=b.length,d=0;d<c&&b[d]!=a;)d++;d<c&&this._hashChangeCallbacks.splice(d,1)},setSeparators:function(a){var b=this.getHashObject(),c=this.__buildRegExpFromArray(["#","%","^","[","]","{","}","\\",'"',"<",">","="]);if(this._typeUtil.isString(a))a=[a];else if(!this._typeUtil.isArray(a))return;for(var d=0,e=a.length;d<e;d++)if(a[d].match(c)){this.$logError(this.INVALID_SEPARATOR,a[d]);return}this._separators=a;this._separatorRegExp=this.__buildRegExpFromArray(this._separators);this._nonEncodableSeparators=
this.__getNonEncodedSeparators(this._separators);this._nonEncodableSepRegExp=this.__buildRegExpFromArray(this._nonEncodableSeparators);aria.utils.Object.isEmpty(b)||this.setHash(b)},addSeparators:function(a){var b=this._separators;if(this._typeUtil.isString(a))a=[a];else if(!this._typeUtil.isArray(a))return;for(var c=0,d=a.length;c<d;c++)aria.utils.Array.contains(this._separators,a[c])||b.push(a[c]);this.setSeparators(b)},setIE7polling:function(a){a&&!aria.core.Browser.isIE7&&this.$logWarn(this.INVALID_HASHPOLLING_TRIGGER);
if((a=a&&aria.core.Browser.isIE7)&&!this._enableIE7polling){this._enableIE7polling=a;this._hashPoll()}else this._enableIE7polling=a},_stringifyHashObject:function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(encodeURIComponent(c)+"="+encodeURIComponent(a[c]));return b.join(this._separators[0])},_extractHashObject:function(a){var b={},c,d;a=a?a.split(this._separatorRegExp):[];for(var e=0,f=a.length;f>e;e++){d=a[e];c=decodeURIComponent(d).split("=");if(c.length==2)b[c[0]]=c[1];else if(d.indexOf("=")==
d.length)b[c[0]]="";else b["param"+e]=c[0]}return b},_addHashChangeInternalCallback:function(){this._hashPoll();aria.core.Browser.isIE7||aria.utils.Event.addListener(window,"hashchange",{fn:this._internalCallback,scope:this},true)},_hashPoll:function(){if(this._enableIE7polling){aria.core.Timer.addCallback({fn:this._hashPoll,scope:this,delay:this.ie7PollDelay});this.getHashString()!=this._currentHashString&&this._internalCallback()}},_internalCallback:function(){var a=this._hashChangeCallbacks,b;
this._currentHashString=this.getHashString();for(var c=this._extractHashObject(this._currentHashString),d=0,e=a.length;e>d;d++){b=a[d];b=this.$normCallback(b);this.$callback(b,c)}},_removeHashChangeInternalCallback:function(){aria.core.Browser.isIE7||aria.utils.Event.removeListener(window,"hashchange",{fn:this._internalCallback})},_validateHashObject:function(a){var b,c=this._nonEncodableSepRegExp,d;for(d in a)if(a.hasOwnProperty(d))if(c&&d.match(c)){this.$logError(this.INVALID_HASHOBJECT_KEY,[d,
this._nonEncodableSeparators.join("")]);return false}else{b=a[d];if(this._typeUtil.isString(b)){if(c&&b.match(c)){this.$logError(this.INVALID_HASHOBJECT_VALUE,[b,d,this._nonEncodableSeparators.join("")]);return false}}else{this.$logError(this.INVALID_HASHOBJECT_TYPE,d);return false}}return true},__getNonEncodedSeparators:function(a){for(var b=[],c=0,d=a.length;c<d;c++)a[c]==encodeURIComponent(a[c])&&b.push(a[c]);return b},__buildRegExpFromArray:function(a){for(var b=/([\^\$\.\*\+\?\=\!\:\|\\\/\(\)\[\]\{\}]){1,1}/g,
c=[],d=0,e=a.length;d<e;d++)c.push(a[d].replace(b,"\\$1"));return c.length==0?null:RegExp(c.join("|"))}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/IdManager.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.IdManager",$dependencies:["aria.utils.Array"],$constructor:function(a){this._freeIdMap={};this._idCounter=0;this.prefix=a||""},$destructor:function(){this._freeIdMap=null},$prototype:{getId:function(){for(var a in this._freeIdMap)if(this._freeIdMap.hasOwnProperty(a)){delete this._freeIdMap[a];return a}a=this.prefix+this._idCounter;this._idCounter++;return a},releaseId:function(a){if(a)this._freeIdMap[a]=true}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Math.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.Math",$singleton:true,$dependencies:["aria.utils.Type"],$constructor:function(){this.utilType=aria.utils.Type},$prototype:{normalize:function(a,c,b){var d=this.utilType.isNumber;if(!d(a))return a;if(d(c))a=Math.max(a,c);if(d(b))a=Math.min(a,b);return a},min:function(a,c){var b=this.utilType.isNumber,d=b(a);b=b(c);if(!d&&!b)return null;else if(d){if(!b)return a}else return c;return Math.min(a,c)},max:function(a,c){var b=this.utilType.isNumber,d=b(a);b=b(c);
if(!d&&!b)return null;else if(d){if(!b)return a}else return c;return Math.max(a,c)}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Number.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.Number",$singleton:true,$dependencies:["aria.utils.environment.Number","aria.utils.String","aria.utils.Type","aria.utils.Array"],$constructor:function(){this._validDigits=/^(\-|\.|\+)?\d+(\.)?(\d+)?$/;this._digitsOnly=/^\d+$/;this._validCurrency=/^([\u00A4])?([,#0]+)(?:\.([#0]+))?([\u00A4])?$/;this._regExSpecials=RegExp("(\\"+"/.*+?|()[]{}\\".split("").join("|\\")+")","g");this._grouping=this._decimal=this._replaceDecimal=this._removeGrouping=null;this._strictGrouping=
true;this._currency=this._format=null;this._cache={};this._formatCache={};aria.core.AppEnvironment.$on({changingEnvironment:{fn:this._appEnvChanged,scope:this}});this._appEnvChanged.call(this)},$destructor:function(){this._formatCache=null},$statics:{INVALID_FORMAT_TYPE:"Application config format can only be a string or a function",DEPRECATED:"The method '%1' is deprecated. Please check the API docs for alternatives",INVALID_FORMAT:"The format used for %1 is invalid, please check bean %2",DECIMAL_BEAN:"aria.utils.environment.NumberCfgBeans.DecimalFormatSymbols",
CURRENCY_BEAN:"aria.utils.environment.NumberCfgBeans.CurrencyFormatsCfg"},$prototype:{toNumber:function(a){if(!this._validDigits.test(a))return null;return Number(a)},interpretNumber:function(a,b,c){var e=this._explode(b);b="";var d,f,h,i=e.regularGroup,g=!!c;c=this._normalizeSymbols(c);d=c.groupingSeparator;f=c.decimalSeparator;h=c.strictGrouping;c=g?this._buildRegEx(d,f):{group:this._removeGrouping,decimal:this._replaceDecimal};g=a.charAt(0);if(g==="+"||g==="-"){b=g;a=a.substring(1);g=a.charAt(0)}var k=
a.lastIndexOf(d);if(k>-1){var l=a.indexOf(f);if(l>-1&&l<k)return null;if(g===d)return null;if(h){if(!e.hasGrouping)return null;var j;d=a.split(d);if(i===0){j=e.integer.split(",");if(j.length<d.length)return null}e=d[0];if(i>0&&e.length>i||!this._digitsOnly.test(e))return null;for(h=d.length-2;h>0;h-=1){e=d[h];g=i||j[h].length;if(e.length!==g||e.indexOf(f)!==-1)return null}e=d[d.length-1];g=i||j[j.length-1].length;if(e.length!==g&&e.charAt(g)!==f)return null}}a=b+a.replace(c.group,"");if(f!=="."&&
a.indexOf(".")!==-1)return null;a=a.replace(c.decimal,".");if(!this._validDigits.test(a))return null;return a},formatNumber:function(a,b,c){if(isNaN(a))return a;a=Number(a);c=this._normalizeSymbols(c);b=this._explode(b);if(!b)return this.$logError(this.INVALID_FORMAT,["formatCurrency",this.CURRENCY_BEAN]);var e=Math.abs(a).toString().split("."),d=Math.abs(a).toFixed(b.maxDecLen).split(".");a=a<0?"-":"";var f=d[0];e=e[1]||"";d=d[1]||"";if(f.length<b.minIntLen)f=aria.utils.String.pad(f,b.minIntLen,
"0",true);if(d.length!==e.length)d=aria.utils.String.crop(d,b.minDecLen,"0");b=[a+this._addGrouping(f,b,c)];d&&b.push(d);return b.join(c.decimalSeparator)},formatCurrency:function(a,b,c){c=this._normalizeSymbols(c);var e=this._explode(b);if(!e)return this.$logError(this.INVALID_FORMAT,["formatCurrency",this.CURRENCY_BEAN]);var d=this._currency;a=this.formatNumber(a,b,c);return e.currencyBegin?d+a:e.currencyEnd?a+d:a},isValidPattern:function(a){return!!this._explode(a)},_appEnvChanged:function(a){var b=
aria.utils.Array;if(!a||!a.changedProperties||b.contains(a.changedProperties,"decimalFormatSymbols")||b.contains(a.changedProperties,"currencyFormats")){b=aria.utils.environment.Number.getDecimalFormatSymbols();a=aria.utils.environment.Number.getCurrencyFormats();var c=this._buildRegEx(b.groupingSeparator,b.decimalSeparator);if(c.valid){this._removeGrouping=c.group;this._replaceDecimal=c.decimal;this._decimal=b.decimalSeparator;this._grouping=b.groupingSeparator;this._strictGrouping=b.strictGrouping}b=
aria.utils.Type;if(!b.isString(a.currencyFormat)&&!b.isFunction(a.currencyFormat))this.$logError(this.INVALID_FORMAT,["currencyFormat",this.CURRENCY_BEAN]);else{this._format=a.currencyFormat;this._currency=a.currencySymbol}}},_buildRegEx:function(a,b){var c={valid:true};if(!a||a.length>1||/\d/.test(a)){this.$logError(this.INVALID_FORMAT,["groupingSeparator",this.DECIMAL_BEAN]);c.valid=false}if(!b||b.length>1||/\d/.test(b)){this.$logError(this.INVALID_FORMAT,["decimalSeparator",this.DECIMAL_BEAN]);
c.valid=false}if(a===b){this.$logError(this.INVALID_FORMAT,["decimalSeparator",this.DECIMAL_BEAN]);c.valid=false}if(c.valid){c.group=RegExp(a.replace(this._regExSpecials,"\\$1"),"g");c.decimal=RegExp(b.replace(this._regExSpecials,"\\$1"))}return c},_normalizeSymbols:function(a){if(a){a.decimalSeparator=a.decimalSeparator||this._decimal;a.groupingSeparator=a.groupingSeparator||this._grouping;a.strictGrouping=a.strictGrouping!=null?a.strictGrouping:this._strictGrouping}else a={decimalSeparator:this._decimal,
groupingSeparator:this._grouping,strictGrouping:this._strictGrouping};return a},_explode:function(a){if(!a)a=this._format;var b=aria.utils.Type;if(b.isFunction(a))a=a();if(b.isString(a)){if(b=this._cache[a])return b;var c=this._validCurrency.exec(a);if(c){b={currencyBegin:!!c[1],currencyEnd:!!c[4],integer:c[2],decimal:c[3]||""};c=b.integer.replace(/,/g,"");var e=c.indexOf("0");b.minIntLen=e>-1?c.length-e:0;b.hasGrouping=c.length!=b.integer.length;if(b.hasGrouping)if(b.integer.length-c.length===1)b.regularGroup=
b.integer.length-b.integer.indexOf(",")-1;else{c=b.integer.split(",");e=b.integer.length-b.integer.lastIndexOf(",")-1;for(var d=1,f=c.length;d<f;d+=1)if(c[d].length!=e){e=0;break}b.regularGroup=e}b.minDecLen=b.decimal.lastIndexOf("0")+1;b.maxDecLen=b.decimal.length}return this._cache[a]=b}},_addGrouping:function(a,b,c){if(!b.hasGrouping)return a;c=c.groupingSeparator;var e=b.integer,d=b.regularGroup;b=[];if(d>0)b=d;else{e=e.split(",");for(d=e.length-1;d>0;d-=1)b.push(e[d].length)}return aria.utils.String.chunk(a,
b).join(c)},formatAfterDecimalPlace:function(a,b){this.$logWarn(this.DEPRECATED,"formatAfterDecimalPlace");a=parseFloat(a);return a.toFixed(b)},addCommas:function(a,b){this.$logWarn(this.DEPRECATED,"addCommas");a+="";var c=a.split("."),e=c[0];c=c.length>1?"."+c[1]:"";for(var d=RegExp("(\\d+)(\\d{"+b+"})");d.test(e);)e=e.replace(d,"$1,$2");return e+c},processNumberPattern:function(a){this.$logWarn(this.DEPRECATED,"processNumberPattern");if(!this._formatCache[a]){if(typeof a==="function")a=a();else typeof a!==
"string"&&this.$logError(this.INVALID_FORMAT_TYPE);var b=/^([\u00A4])?([,#0]+)?([0#])([.0#]*)?([\u00A4])?$/.exec(a);this._formatCache[a]=b}return this._formatCache[a]},toSizedString:function(a,b){this.$logError(this.DEPRECATED,"toSizedString");for(var c=String(a);c.length<b;)c="0"+c;return c},_isValidNumber:function(a){this.$logWarn(this.DEPRECATED,"_isValidNumber");return this._validDigits.test(a)}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/overlay/LoadingOverlay.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.overlay.LoadingOverlay",$dependencies:["aria.utils.Dom"],$constructor:function(b,c,a){c=this.__createOverlay(c,a);this.__appendToDOM(c);this.__setInPosition(b,c);this.__computeZIndex(b,c);this.overlay=c;this.element=b},$destructor:function(){this.overlay.parentNode.removeChild(this.overlay);this.element=this.overlay=null},$prototype:{__createOverlay:function(b,c){var a=document.createElement("DIV");a.id="xOverlay"+b;a.className="xLDI";a.style.position=
"fixed";if(c)a.innerHTML="<span class='xLDI-text'>"+c+"</span>";return a},__appendToDOM:function(b){document.body.appendChild(b)},__setInPosition:function(b,c){var a=aria.utils.Dom.getGeometry(b),d=c.style;if(a){d.top=a.y+"px";d.left=a.x+"px";d.width=a.width+"px";d.height=a.height+"px";d.display="block"}else d.display="none"},__computeZIndex:function(b,c){for(var a=2E4,d=document.body;b&&b!=d;){var e=b.style.zIndex;if(e){e=parseInt(e,10);if(e>a)a=e+1}b=b.parentNode}c.style.zIndex=""+a},refreshPosition:function(){this.__setInPosition(this.element,
this.overlay)},refresh:function(){this.__setInPosition(this.element,this.overlay);this.__computeZIndex(this.element,this.overlay)}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Path.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.Path",$dependencies:["aria.utils.String"],$singleton:true,$constructor:function(){},$statics:{WRONG_PATH_SYNTAX:"Syntax for path %1 is not valid. Note that variables cannot be used in paths.",RESOLVE_FAIL:"Resolve for path %1 failed, root element does not contain this path"},$prototype:{resolve:function(a,b){if(aria.utils.Type.isString(a))a=this.parse(a);if(aria.utils.Type.isArray){for(var c=0,d,e=a.length;c<e;c++){d=a[c];b=b[d];if(!b&&c!=e-1)throw{error:this.RESOLVE_FAIL,
args:[a],object:b};}return b}throw{error:this.RESOLVE_FAIL,args:[a],object:b};},parse:function(a){return this._paramParse("."+a)},_paramParse:function(a){if(!a)return[];var b=a.charAt(0),c,d;if(b=="["){c=a.indexOf("]");if(c!=-1){b=a.substring(1,c);d=a.substring(c+1);if(/^\d+$/.test(b)){a=this._paramParse(d);a.unshift(b);return a}else{c=b.charAt(0);var e=aria.utils.String;if((c=="'"||c=='"')&&e.indexOfNotEscaped(b,c,1)==b.length-1){a=this._paramParse(d);a.unshift(b.substring(1,b.length-1).replace(RegExp("\\\\"+
c,"gi"),c));return a}}}}else if(b=="."){b=/^[_A-z]\w*/.exec(a.substring(1));if(b.length){b=b[0];d=a.substring(b.length+1);a=this._paramParse(d);a.unshift(b);return a}}throw{error:this.WRONG_PATH_SYNTAX,args:[a]};},pathArrayToString:function(a){for(var b=[a[0]],c=1,d=a.length;c<d;c++)b.push('["'+a[c].replace(/"/gi,'\\"')+'"]');return b.join("")}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/ProfilingDisplay.tpl
//MJhO76UFv6
// Display for profile informations
{Template {
	$classpath:'aria.utils.ProfilingDisplay',
	$hasScript: true
}}

	{var leftShift = 300/}
	{var scale = 2/}
	{var showAllMsg = true/}
	{var timeBegin = 0/}
	{var verticalBarTime1 = -1/}
	{var verticalBarTime2 = -1/}
	{var marginLeft = 5/}

	{macro main()}
		<div style="background:#ACC2FF;border-bottom:solid 2px black;padding:5px;width:${Math.max(getLength(data._max,0)+leftShift+30, 500)}px;color:white">
			<span {on click close/} style="cursor:pointer; padding-left:5px">
				{@aria:Icon {			
					icon : 'std:close',
					tooltip: "Close profiling data"
				}/}
			</span>
			<span {on click zoomOut/} style="cursor:pointer; padding-left:5px">
				{@aria:Icon {			
					icon : 'std:zoom_out',
					tooltip: "Zoom out"
				}/}
			</span>
			<span {on click zoomIn/} style="cursor:pointer; padding-left:5px">
				{@aria:Icon {			
					icon : 'std:zoom_in',
					tooltip: "Zoom in"
				}/}
			</span>
			<span {on click toggleChecked/} style="cursor:pointer; padding-left:5px">
				{@aria:Icon {			
					icon : 'std:validated',
					tooltip: "Show all/only selected items"
				}/}
			</span>
			<span {on click resetTimeOrigin/} style="cursor:pointer; padding-left:5px">
				{@aria:Icon {			
					icon : 'std:undo',
					tooltip: "Reset time origin"
				}/}
			</span>
		</div>
		<div {on mousedown mouseDown/} style="position:relative;">
			{foreach cat in data} 
				{if cat_index!='_max'}
					{if showAllMsg || cat['view:visible']}
						<div style="width:${getLength(data._max,0)+leftShift+30}px;border-bottom:solid 1px grey;margin:${marginLeft}px 0 15px 5px">
							<h2>{call displayCheckBox(cat)/} ${cat_index}</h2>	
							{foreach msg in cat}
								{if msg_index.indexOf('view:') != 0 && (showAllMsg || msg['view:visible']) && isTimeRangeListVisible(msg)}
									<div style="position:relative; height:14px; width:100%;border-top:dashed 1px #EEE;font-size:xx-small;">
										{call displayCheckBox(msg)/} ${msg_index} (${msg[0]}ms) 
										{for var i=1; i<msg.length;i++}
											{var log = msg[i]/}
											{if isTimeRangeVisible(log.start, log.length)}
												<div style="position:absolute;top:0;
															overflow:hidden;
															left:${getPosition(log.start)}px;
															width:${getLength(log.length,log.start)}px;
															height:14px;
															background:#ACC2FF;
															border-left:solid 1px black"
													title="start: ${log.start}ms; length: ${log.length}ms; ${msg_index} (${cat_index})">${log.length}</div>
											{/if}
										{/for}
									</div>
								{/if}
							{/foreach}
						</div>
					{/if}
				{/if}
			{/foreach}
			{section {
				id: "verticalBars",
				macro: "displayVerticalBars"
			}/}
		</div>

	{/macro}
	
	{macro displayCheckBox(item)}
		{if showAllMsg}
			<span style="position:relative;top:-4px;vertical-align:middle;">
				{@aria:CheckBox {
					bind: {
						value: {
							to: 'view:visible',
							inside: item
						}
					}
				}/}
			</span>
		{/if}
	{/macro}
	
	{macro displayVerticalBars()}
		{var timeDiff=Math.abs(verticalBarTime1-verticalBarTime2)/}
		{if isTimeRangeVisible(verticalBarTime1, 0)}
			<div style="position:absolute;left:${getPosition(verticalBarTime1)+marginLeft}px;top:0px;width:1px;height:100%;background-color:#C0C0C0;" title="ctrl marker position: ${verticalBarTime1}ms; ${timeDiff}ms between markers">&nbsp;</div>
		{/if}
		{if isTimeRangeVisible(verticalBarTime2, 0)}
			<div style="position:absolute;left:${getPosition(verticalBarTime2)+marginLeft}px;top:0px;width:1px;height:100%;background-color:#C0C0C0;" title="shift marker position: ${verticalBarTime2}ms; ${timeDiff}ms between markers">&nbsp;</div>
		{/if}
	{/macro}

{/Template}
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/ProfilingDisplayScript.js
//MJhO76UFv6
Aria.tplScriptDefinition({$classpath:"aria.utils.ProfilingDisplayScript",$prototype:{zoomIn:function(){this.scale/=2;this.$refresh()},zoomOut:function(){this.scale*=2;this.$refresh()},close:function(){aria.utils.Profiling.hideProfilingData()},getPosition:function(a){if(a<this.timeBegin)return this.leftShift;return(a-this.timeBegin)/this.scale+this.leftShift},getLength:function(a,b){var c=b-this.timeBegin;if(c<0)a+=c;if(a<=0)return 0;return a/this.scale},isTimeRangeVisible:function(a,b){return a+b>=
this.timeBegin},isTimeRangeListVisible:function(a){for(var b=1;b<a.length;b++)if(this.isTimeRangeVisible(a[b].start,a[b].length))return true;return false},getTimeFromPosition:function(a){return(a-this.leftShift)*this.scale+this.timeBegin},toggleChecked:function(){this.showAllMsg=!this.showAllMsg;this.$refresh()},mouseDown:function(a){var b=aria.utils.Dom.calculatePosition(aria.utils.Profiling._displayDiv.firstChild);b=a.clientX-b.left;if(aria.core.Browser.isIE7)b-=2;b=this.getTimeFromPosition(b-this.marginLeft);
if(!(b<this.timeBegin)){if(a.altKey&&!a.ctrlKey&&!a.shiftKey){this.timeBegin=b;this.$refresh()}else if(a.altKey)return;else{if(a.ctrlKey&&!a.shiftKey)this.verticalBarTime1=b;else if(a.shiftKey&&!a.ctrlKey)this.verticalBarTime2=b;else return;this.$refresh({outputSection:"verticalBars"})}a.preventDefault(true)}},resetTimeOrigin:function(){this.timeBegin=0;this.$refresh()}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Rand.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.Rand",$singleton:true,$constructor:function(a){this.m=Math.pow(2,48);this.a=25214903917;this.c=11;this.last=a==undefined?12483:a},$prototype:{rand:function(){var a=(this.a*this.last+this.c)%this.m;return this.last=a},rand01:function(){return this.rand()/this.m}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Size.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.Size",$dependencies:["aria.utils.Math"],$singleton:true,$constructor:function(){this._domContainer=null},$destructor:function(){this._domContainer=null},$prototype:{getSize:function(a){return{width:a.offsetWidth,height:a.offsetHeight}},getFreeSize:function(a){if(!this._domContainer)this._domContainer=this.__createDomContainer();this.getFreeSize=this.__getFreeSize;return this.getFreeSize(a)},__createDomContainer:function(){var a=document.createElement("div");
a.style.cssText="position:absolute;top:0px;left:0px;visibility:hidden;display:block;width:0px;height:0px;";return document.body.appendChild(a)},__getFreeSize:function(a){var c=a.parentNode;this._domContainer.appendChild(a);var d={width:a.offsetWidth,height:a.offsetHeight};aria.utils.Type.isHTMLElement(c)&&c.appendChild(a);return d},setContrains:function(a,c,d){var e,b,f={},g=false,h=false;if(c){e=a.offsetWidth;b=aria.utils.Math.normalize(e,c.min,c.max);if(b!=e){a.style.width=b+"px";g=true}f.width=
b}if(d){e=a.offsetHeight;b=aria.utils.Math.normalize(e,d.min,d.max);if(b!=e){a.style.height=b+"px";h=true}f.height=b}if(g||h){if(!c)f.width=a.offsetWidth;if(!d)f.height=a.offsetHeight;return f}return null}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/StackHashMap.js
//MJhO76UFv6
(function(){var g=0,f;Aria.classDefinition({$classpath:"aria.utils.StackHashMap",$dependencies:["aria.utils.Type"],$onload:function(){f=aria.utils.Type},$onunload:function(){f=null},$constructor:function(){g++;this._nextIndex=0;this._otherKeys=this._numberKeys=this._stringKeys=this._objectKeys=null;this._metaDataName=Aria.FRAMEWORK_PREFIX+"hash::"+g},$destructor:function(){this.removeAll()},$beans:{Entry:{$type:"json:Object",$description:"Structure used to store a (key, value) pair in a StackHashMap object.",
$properties:{key:{$type:"json:MultiTypes",$description:"Key of the entry."},value:{$type:"json:MultiTypes",$description:"Value of the entry."},next:{$type:"Entry",$description:"Link to the entry with the same key, which was present before adding this entry, if any, or undefined otherwise."},index:{$type:"json:MultiTypes",$description:"Index of this entry in _objectKeys, _stringKeys, _numberKeys, or _otherKeys."}}}},$prototype:{_getMap:function(a,d){if(f.isString(a)){if(!this._stringKeys&&d)this._stringKeys=
{};return this._stringKeys}else if(f.isNumber(a)){if(!this._numberKeys&&d)this._numberKeys={};return this._numberKeys}else if(a!=null&&(typeof a=="object"||f.isFunction(a))){if(!this._objectKeys&&d)this._objectKeys={};return this._objectKeys}else{if(!this._otherKeys&&d)this._otherKeys={};return this._otherKeys}},push:function(a,d){var b={key:a,value:d,index:this._nextIndex};this._nextIndex++;var c=this._getMap(a,true);if(c==this._objectKeys){var e=a[this._metaDataName];if(e){b.next=e;b.index=e.index}a[this._metaDataName]=
b}else if(c!=this._otherKeys){b.index=a;b.next=c[b.index]}else for(e in c)if(c.hasOwnProperty(e)){var h=c[e];if(a===h.key){b.index=e;b.next=h;break}}c[b.index]=b},pop:function(a){var d=this._getMap(a,false);if(d!=null){var b;if(d==this._objectKeys){if(b=a[this._metaDataName])(a[this._metaDataName]=b.next)||delete a[this._metaDataName]}else if(d!=this._otherKeys)b=d[a];else for(var c in d)if(d.hasOwnProperty(c)){var e=d[c];if(a===e.key){b=e;break}}if(b){a=b.next;(d[b.index]=a)||delete d[b.index];b.key=
null;b.next=null;return b.value}}},_removeAllToArray:function(a,d){if(a!=null)for(var b in a){var c=a[b],e=c.key;if(a==this._objectKeys){e[this._metaDataName]=null;delete c.key[this._metaDataName]}for(;c;){d.push(c.value);c.value=null;c.key=null;e=c.next;c.next=null;c=e}a[b]=null;delete a[b]}},removeAll:function(){var a=[];this._removeAllToArray(this._objectKeys,a);this._objectKeys=null;this._removeAllToArray(this._stringKeys,a);this._stringKeys=null;this._removeAllToArray(this._numberKeys,a);this._numberKeys=
null;this._removeAllToArray(this._otherKeys,a);this._otherKeys=null;return a}}})})();
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Store.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.Store",$dependencies:["aria.utils.Array","aria.utils.Callback"],$constructor:function(){this._store=null;this._storeLength=0},$destructor:function(){var b;if(this._store){for(var a=0,c=this._store.length;a<c;a++){b=this._store[a];b.$dispose&&b.$dispose()}this._store=null}},$prototype:{add:function(b){if(!this._store){this._store=[];this.initialize()}this._store[this._storeLength++]=b},initialize:function(){},remove:function(b){if(this._store&&aria.utils.Array.remove(this._store,
b)){this._storeLength--;return true}return false},getSize:function(){return this._storeLength},getMatch:function(b,a){a=a===true;for(var c=null,d=a?[]:null,e=0,f=0;f<this._storeLength;f++){c=this._store[f];if(this.$callback(b,c)){if(!a)return c;d[e++]=c}}return d},removeMatch:function(b,a){b=new aria.utils.Callback(b);a=a===true;for(var c=null,d=a?[]:null,e=0;e<this._storeLength;e++){c=this._store[e];if(b.call(c)){this._store.splice(e,1);this._storeLength--;e-=1;if(!a){b.$dispose();return c}d.push(c)}}b.$dispose();
return d},foreach:function(b,a){var c=null;b=new aria.utils.Callback(b);if(a)a=new aria.utils.Callback(a);for(var d=0;d<this._storeLength;d++){c=this._store[d];a&&!a.call(c)||b.call(c)}b.$dispose();a&&a.$dispose()}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/String.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.String",$singleton:true,$dependencies:["aria.utils.Type","aria.utils.Json"],$constructor:function(){},$prototype:{trim:String.trim?String.trim:function(a){return a.replace(/^\s+|\s+$/g,"")},isEscaped:function(a,c){for(var b=false,d=c-1;d>=0;d--)if(a.charAt(d)=="\\")b=!b;else break;return b},indexOfNotEscaped:function(a,c,b){for(b=a.indexOf(c,b);b!=-1;){if(!this.isEscaped(a,b))return b;b=a.indexOf(c,b+1)}return-1},escapeHTML:function(a){return a.replace(/&/g,
"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},stripAccents:function(a){a=a.replace(/[\u00E0\u00E2\u00E4]/gi,"a");a=a.replace(/[\u00E9\u00E8\u00EA\u00EB]/gi,"e");a=a.replace(/[\u00EE\u00EF]/gi,"i");a=a.replace(/[\u00F4\u00F6]/gi,"o");return a=a.replace(/[\u00F9\u00FB\u00FC]/gi,"u")},nextWhiteSpace:function(a,c,b){for(var d=/\s/,f;c<b;){f=a.charAt(c);if(d.test(f))return c;c++}return-1},stringify:function(a){return'"'+a.replace(/([\\\"])/g,"\\$1").replace(/(\r)?\n/g,"\\n")+'"'},endsWith:function(a,
c){return a.indexOf(c,a.length-c.length)!==-1},encodeForQuotedHTMLAttribute:function(a){return a?a.replace(/"/g,"&quot;"):""},capitalize:function(a){return a.charAt(0).toUpperCase()+a.slice(1)},pad:function(a,c,b,d){a=""+a;var f=a.length;if(f<c){var e=[];for(c-=f;c>0;c-=1)e.push(b);if(d===true)a=e.join("")+a;else a+=e.join("")}return a},crop:function(a,c,b,d){if(d===true){d=0;for(c=a.length-c;d<c;d+=1)if(a.charAt(d)!==b)break;return a.substring(d)}else{for(d=a.length-1;d>=c;d-=1)if(a.charAt(d)!==
b)break;return a.substring(0,d+1)}},chunk:function(a,c,b){if(aria.utils.Type.isString(a)){if(!a)return[a]}else return null;return aria.utils.Type.isArray(c)?this._chunkArray(a,c,b):this._chunkNumber(a,c,b)},_chunkNumber:function(a,c,b){var d=[],f=a.length;if(c<1||c>=f)return[a];else if(c===1)return a.split("");if(b===true){for(b=0;b<f;){d.push(a.substr(b,c));b+=c}return d}else{for(b=f;b>0;){d.push(a.substring(Math.max(0,b-c),b));b-=c}return d.reverse()}},_chunkArray:function(a,c,b){var d=[],f=a.length,
e,g;if(b===true){e=b=0;for(g=c.length;e<g;e+=1){d.push(a.substr(b,c[e]));b+=c[e];if(b>=f)break}b<f&&d.push(a.substring(b));return d}else{b=f;e=0;for(g=c.length;e<g;e+=1){d.push(a.substring(Math.max(0,b-c[e]),b));b-=c[e];if(b<=0)break}b>0&&d.push(a.substring(0,b));return d.reverse()}}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/UtilsRes.js
//MJhO76UFv6
Aria.resourcesDefinition({$classpath:"aria.utils.UtilsRes",$resources:{timeFormatLabels:{am:"AM",pm:"PM"}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/Alpha.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.validators.Alpha",$extends:"aria.utils.validators.RegExp",$constructor:function(a){this.$RegExp.constructor.call(this,this.ALPHA_REGEXP,a)},$statics:{ALPHA_REGEXP:/^[A-Za-z]+$/,DEFAULT_LOCALIZED_MESSAGE:"Invalid ALPHA string."},$prototype:{}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/AlphaInternational.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.validators.AlphaInternational",$extends:"aria.utils.validators.RegExp",$constructor:function(a){this.$RegExp.constructor.call(this,this.ALPHAINTERNATIONAL_REGEXP,a)},$statics:{ALPHAINTERNATIONAL_REGEXP:/^[A-Za-z0-9 \'\.\-\u00E0\u00C0\u00E1\u00C1\u00E2\u00C2\u00E3\u00C3\u00E4\u00C4\u00E5\u00C5\u00E6\u00C6\u00E7\u00C7\u00E8\u00C8\u00E9\u00C9\u00EA\u00CA\u00EB\u00CB\u00EC\u00CC\u00ED\u00CD\u00EE\u00CE\u00EF\u00CF\u00F0\u00D0\u00F1\u00D1\u00F2\u00D2\u00F3\u00D3\u00F4\u00D4\u00F5\u00D5\u00F6\u00D6\u00F8\u00D8\u00F9\u00D9\u00FA\u00DA\u00FB\u00DB\u00FC\u00DC\u00FD\u00DD\u00FE\u00DE\u00FF\u00DF]+$/,
DEFAULT_LOCALIZED_MESSAGE:"Invalid ALPHAINTERNATIONAL string."},$prototype:{}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/AlphaNum.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.validators.AlphaNum",$extends:"aria.utils.validators.RegExp",$constructor:function(a){this.$RegExp.constructor.call(this,this.ALPHANUM_REGEXP,a)},$statics:{ALPHANUM_REGEXP:/^[A-Za-z0-9]+$/,DEFAULT_LOCALIZED_MESSAGE:"Invalid ALPHANUM string."},$prototype:{}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/CfgBeans.js
//MJhO76UFv6
Aria.beanDefinitions({$package:"aria.utils.validators.CfgBeans",$description:"Beans used in validators and in the error widget.",$namespaces:{json:"aria.core.JsonTypes"},$beans:{MessagesList:{$type:"json:Array",$description:"List of messages.",$contentType:{$type:"Message"}},Message:{$type:"json:Object",$description:"Structure to store a message to be displayed to the user, with type, code, localized message, optional sub-messages...",$properties:{type:{$type:"json:String",$description:"Type of message, may be aria.utils.Data.TYPE_WARNING, aria.utils.Data.TYPE_ERROR or aria.utils.Data.TYPE_INFO. Other types are accepted as well.",
$default:"E"},localizedMessage:{$type:"json:String",$mandatory:true,$description:"Message in user language."},code:{$type:"json:String",$mandatory:false,$description:"Language-independent error code."},fieldRef:{$type:"json:String",$mandatory:false,$description:"Path to a value in the data model which the message refers to."},metaDataRef:{$type:"json:ObjectRef",$mandatory:false,$description:"Reference to the meta-data structure of the value in the data model which the message refers to."},subMessages:{$type:"MessagesList",
$mandatory:false,$description:"List of messages which describe in more details this message."}}}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/Email.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.validators.Email",$extends:"aria.utils.validators.RegExp",$constructor:function(a){this.$RegExp.constructor.call(this,this.EMAIL_REGEXP,a)},$statics:{EMAIL_REGEXP:/^[A-Za-z0-9!#$%&;'=^_~\*\+\-\/\?\`\{\|\}]+(?:\.[A-Za-z0-9!#$%&;'~=^_\*\+\-\/\?\`\{\|\}]+)*@(?:[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?\.)+[A-Za-z0-9](?:[A-Za-z0-9\-]*[A-Za-z0-9])?$/,DEFAULT_LOCALIZED_MESSAGE:"Invalid e-mail."},$prototype:{}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/IValidator.js
//MJhO76UFv6
Aria.interfaceDefinition({$classpath:"aria.utils.validators.IValidator",$interface:{validate:"Function"}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/Mandatory.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.validators.Mandatory",$extends:"aria.utils.validators.Validator",$constructor:function(a){this.$Validator.constructor.call(this,a)},$destructor:function(){this.$Validator.$destructor.call(this)},$statics:{DEFAULT_LOCALIZED_MESSAGE:"This field is a mandatory field."},$prototype:{validate:function(a){if(a)return this._validationSucceeded();return this._validationFailed()}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/MinMaxLength.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.validators.MinMaxLength",$extends:"aria.utils.validators.Validator",$constructor:function(a,b,c){this.$Validator.constructor.call(this,c);this.minLength=a;this.maxLength=b;if(isNaN(parseInt(this.minLength,10))||isNaN(parseInt(this.maxLength,10)))this.$logError(this.MISSING_MIN_MAX_VALUES)},$destructor:function(){this.maxLength=this.minLength=null;this.$Validator.$destructor.call(this)},$statics:{DEFAULT_LOCALIZED_MESSAGE:"The value must be more than the minimum length and less than the maximum length of characters long.",
MISSING_MIN_MAX_VALUES:"There was a problem loading the MinMaxLength validator, MIN and MAX values must be passed into the validators constructor."},$prototype:{validate:function(a){if(a==null||a==="")return this._validationSucceeded();if(a.length<this.minLength||a.length>this.maxLength)return this._validationFailed();return this._validationSucceeded()}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/MultipleValidator.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.validators.MultipleValidator",$extends:"aria.utils.validators.Validator",$dependencies:["aria.utils.Array","aria.utils.Data"],$constructor:function(b,a,c){this.$Validator.constructor.call(this,b);this.validators=[];this.breakOnMessage=false;this.groupMessages=b!=null;this.groups=a!=null?a:[];this.eventToValidate=c!=null?c:"onsubmit";this.dataUtils=aria.utils.Data},$destructor:function(){this.validators=this.groupMessages=this.breakOnError=null;this.$Validator.$destructor.call(this)},
$prototype:{validate:function(b,a,c){var e=this.validators;if(e.length){for(var d,f=false,g=0;g<e.length;g++)if((f=this.dataUtils.checkGroup(e[g].groups,a))&&this.dataUtils.checkEventToValidate(e[g].eventToValidate,c))if((f=e[g].validate(b,a,c))&&f.length>0){d=d==null?f:d.concat(f);if(this.breakOnMessage)break}if(d&&d.length>0)if(this.groupMessages){b=aria.utils.Json.copy(this.message);b.subMessages=d;return[b]}else return d;return null}},add:function(){for(var b=0,a;a=arguments[b];b++){if(a.validator&&
(a.groups||a.event))this.dataUtils.setValidatorProperties(a.validator,a.groups,a.event);this.validators[this.validators.length]=a.validator?a.validator:a}},remove:function(){for(var b=aria.utils.Array,a=0,c;c=arguments[a];a++)b.remove(this.validators,c)}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/Number.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.validators.Number",$extends:"aria.utils.validators.RegExp",$constructor:function(a){this.$RegExp.constructor.call(this,this.NUM_REGEXP,a)},$statics:{NUM_REGEXP:/^-?[0-9]+([\.,][0-9]+)?$/,DEFAULT_LOCALIZED_MESSAGE:"Invalid NUM string."},$prototype:{}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/Object.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.validators.Object",$dependencies:["aria.utils.Type"],$extends:"aria.utils.validators.Validator",$constructor:function(a){this.$Validator.constructor.call(this,a)},$destructor:function(){this.$Validator.$destructor.call(this)},$prototype:{validate:function(a){if(a===null||aria.utils.Type.isObject(a))return this._validationSucceeded();return this._validationFailed()}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/Phone.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.validators.Phone",$extends:"aria.utils.validators.RegExp",$constructor:function(a){this.$RegExp.constructor.call(this,this.PHONE_REGEXP,a)},$statics:{PHONE_REGEXP:/^[A-Za-z0-9 \-\+\(\)]{2,30}$/,DEFAULT_LOCALIZED_MESSAGE:"Invalid PHONE string."},$prototype:{}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/RegExp.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.validators.RegExp",$extends:"aria.utils.validators.Validator",$constructor:function(a,b){this.$Validator.constructor.call(this,b);this._regexp=a},$destructor:function(){this._regexp=null;this.$Validator.$destructor.call(this)},$prototype:{validate:function(a){if(a==null||a==="")return this._validationSucceeded();if(!this._regexp.test(a))return this._validationFailed();return this._validationSucceeded()}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/String.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.validators.String",$extends:"aria.utils.validators.RegExp",$constructor:function(a){this.$RegExp.constructor.call(this,this.STRING_REGEXP,a)},$statics:{STRING_REGEXP:/^[A-Za-z \-\,\.\'\?\!\:\%\+\=\_\@\;\#\*\(\)\<\>\[\]\/\"]*$/,DEFAULT_LOCALIZED_MESSAGE:"Invalid string."},$prototype:{}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/validators/Validator.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.validators.Validator",$dependencies:["aria.utils.Data"],$implements:["aria.utils.validators.IValidator"],$extends:"aria.core.JsObject",$constructor:function(a){this.localized_message=this.message=null;a?this.setMessage(a):this.setMessage(this.DEFAULT_LOCALIZED_MESSAGE);this.groups=[];this.eventToValidate="onsubmit"},$destructor:function(){this.eventToValidate=this.groups=this.message=null},$statics:{DEFAULT_LOCALIZED_MESSAGE:"Incorrect value."},$prototype:{$init:function(a){a.utilsType=
aria.utils.Type},validate:function(){return this._validationFailed()},setMessage:function(a){if(this.utilsType.isObject(a)){this.message=a;this.localized_message=a.localizedMessage}else if(this.utilsType.isString(a)){this.localized_message=a;this.message=aria.utils.Data.createMessage(a)}},_validationFailed:function(){return[aria.utils.Json.copy(this.message)]},_validationSucceeded:function(){return null}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/VisualFocus.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.VisualFocus",$dependencies:["aria.core.Browser","aria.utils.environment.VisualFocus","aria.utils.Delegate"],$singleton:true,$constructor:function(){this.__style=!aria.core.Browser.isIE6&&!aria.core.Browser.isIE7?aria.utils.environment.VisualFocus.getAppOutlineStyle():null;this.__focusedElement=aria.utils.Delegate.getFocus();this.__previousStyle=this.__outlinedElement=null;aria.utils.environment.VisualFocus.$on({environmentChanged:function(){this.updateOutlineStyle()},
scope:this});aria.utils.Delegate.$on({elementFocused:function(a){this.addVisualFocus(a.focusedElement)},scope:this});aria.utils.Delegate.$on({elementBlurred:function(){this.removeVisualFocus()},scope:this});this.__updateVisualFocus()},$destructor:function(){this.removeVisualFocus();this.__outlinedElement=this.__focusedElement=this.__style=null;aria.utils.Delegate&&aria.utils.Delegate.$unregisterListeners(this);aria.core.environment.Environment&&aria.core.environment.Environment.$unregisterListeners(this)},
$prototype:{addVisualFocus:function(a){this.__focusedElement&&this.removeVisualFocus();this.__focusedElement=a;if(this.__style){if(this.__focusedElement.tagName!="A"&&this.__focusedElement.tagName!="BUTTON"){for(a=this.__focusedElement;a.tagName!="SPAN"&&a!=document.body;a=a.parentNode);if(a!=document.body)this.__outlinedElement=a}else this.__outlinedElement=this.__focusedElement;if(this.__outlinedElement){this.__previousStyle=aria.core.Browser.isIE8?this.__outlinedElement.style.cssText:this.__outlinedElement.style.outline?
this.__outlinedElement.style.outline:"";this.__outlinedElement.style.outline=this.__style}}},removeVisualFocus:function(){if(this.__style&&this.__outlinedElement){if(aria.core.Browser.isIE8)this.__outlinedElement.style.cssText=this.__previousStyle;else this.__outlinedElement.style.outline=this.__previousStyle;this.__previousStyle=this.__outlinedElement=null}this.__focusedElement=null},updateOutlineStyle:function(a){a=a?a:aria.utils.environment.VisualFocus.getAppOutlineStyle();this.__style=!aria.core.Browser.isIE6&&
!aria.core.Browser.isIE7?a:null;this.__updateVisualFocus()},__updateVisualFocus:function(){if(this.__outlinedElement)if(this.__style)this.__outlinedElement.style.outline=this.__style;else{if(aria.core.Browser.isIE8)this.__outlinedElement.style.cssText=this.__previousStyle;else this.__outlinedElement.style.outline=this.__previousStyle;this.__previousStyle=this.__outlinedElement=null}else this.__focusedElement&&this.addVisualFocus(this.__focusedElement)},getStyle:function(){return this.__style}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/utils/Xml.js
//MJhO76UFv6
Aria.classDefinition({$classpath:"aria.utils.Xml",$singleton:true,$constructor:function(){},$prototype:{convertXmlToJson:function(b){var a;if(window.DOMParser)a=(new DOMParser).parseFromString(b,"text/xml");else{a=new ActiveXObject("Microsoft.XMLDOM");a.async="false";a.loadXML(b)}return a.hasChildNodes()?this.__parseXmlNode(a):null},__parseXmlNode:function(b){if(b){for(var a={},e=0;e<b.childNodes.length;e++){var c=b.childNodes[e];if(c.nodeType!=3&&c.nodeType!=4){for(var d=c.nodeName,g=0,f=0;f<b.childNodes.length;f++)if(b.childNodes[f].nodeName==
d)if(++g==2)break;c=this.__parseXmlNode(c);if(g==2){if(a[d]==null)a[d]=[];a[d].push(c)}else a[d]=c}else if(b.childNodes.length==1)a=c.nodeValue}return a}}}});
//MJhO76UFv6
//LOGICAL-PATH:aria/DomEvent.js
//MJhO76UFv6
(function(){var d={target:"srcElement",type:"type",clientX:"clientX",clientY:"clientY",altKey:"altKey",ctrlKey:"ctrlKey",shiftKey:"shiftKey",pageX:"pageX",pageY:"pageY",relatedTarget:"relatedTarget",button:"button"},e;Aria.classDefinition({$classpath:"aria.DomEvent",$dependencies:["aria.core.Browser"],$onload:function(){e=aria.core.Browser.isIE6||aria.core.Browser.isIE7||aria.core.Browser.isIE8;isGecko=!(aria.core.Browser.isIE||aria.core.Browser.isOpera||aria.core.Browser.isChrome||aria.core.Browser.isSafari)},
$constructor:function(a){var c=a.$DomEvent!=null;if(!c&&e&&window.event){a=window.event;for(var b in d)if(d.hasOwnProperty(b))this[b]=a[d[b]];if(a.type=="mouseout")this.relatedTarget=a.toElement;else if(a.type=="mouseover")this.relatedTarget=a.fromElement}else for(b in d)if(d.hasOwnProperty(b))this[b]=a[b];this.type=this.type.toLowerCase();this.keyCode=this.charCode=0;if(this.type=="keydown"||this.type=="keyup"){this.keyCode=a.keyCode;this.isSpecialKey=this.isSpecialKey(this.keyCode,a)}else if(this.type==
"keypress"){b=a.keyCode||a.charCode;var g=isGecko&&a.keyCode;this.keyCode=b;if(!g){this.keyCode=b;if(b>32&&b<38)this.keyCode=b+16;if(b>41&&b<48)this.keyCode=b+64;if(b>47&&b<58)this.keyCode=b+48;if(b>96&&b<123)this.keyCode=b-32}this.charCode=b;this.isSpecialKey=this.isSpecialKey(this.keyCode,a)}else if(this.type=="focusin")this.type="focus";else if(this.type=="focusout")this.type="blur";this.hasStopPropagation=false;this.preventDefault=!c&&e?function(f){a.returnValue=false;f==true&&this.stopPropagation()}:
function(f){a.preventDefault();f==true&&this.stopPropagation()};this.stopPropagation=!c&&e?function(){this.hasStopPropagation=true;a.cancelBubble=true}:function(){this.hasStopPropagation=true;a.stopPropagation()};this._dispose=function(){this.stopPropagation=this.preventDefault=a=null}},$destructor:function(){if(this._dispose){this.delegateTarget=this.target=null;this._dispose()}},$prototype:{_ariaDomEvent:true,_wrapperNumber:0,disposeWrapper:function(){if(this._wrapperNumber==0)this.$dispose();else this._wrapperNumber--},
setTarget:function(a){this.target=a}},$statics:{getWrapper:function(a){if(a&&a._ariaDomEvent){a._wrapperNumber++;return a}else return new aria.DomEvent(a)},KC_BACKSPACE:8,KC_TAB:9,KC_NUM_CENTER:12,KC_ENTER:13,KC_RETURN:13,KC_SHIFT:16,KC_CTRL:17,KC_CONTROL:17,KC_ALT:18,KC_PAUSE:19,KC_CAPS_LOCK:20,KC_ESCAPE:27,KC_SPACE:32,KC_PAGEUP:33,KC_PAGE_UP:33,KC_PAGEDOWN:34,KC_PAGE_DOWN:34,KC_END:35,KC_HOME:36,KC_LEFT:37,KC_ARROW_LEFT:37,KC_UP:38,KC_ARROW_UP:38,KC_RIGHT:39,KC_ARROW_RIGHT:39,KC_DOWN:40,KC_ARROW_DOWN:40,
KC_PRINT_SCREEN:44,KC_INSERT:45,KC_DELETE:46,KC_ZERO:48,KC_ONE:49,KC_TWO:50,KC_THREE:51,KC_FOUR:52,KC_FIVE:53,KC_SIX:54,KC_SEVEN:55,KC_EIGHT:56,KC_NINE:57,KC_A:65,KC_B:66,KC_C:67,KC_D:68,KC_E:69,KC_F:70,KC_G:71,KC_H:72,KC_I:73,KC_J:74,KC_K:75,KC_L:76,KC_M:77,KC_N:78,KC_O:79,KC_P:80,KC_Q:81,KC_R:82,KC_S:83,KC_T:84,KC_U:85,KC_V:86,KC_W:87,KC_X:88,KC_Y:89,KC_Z:90,KC_CONTEXT_MENU:93,KC_NUM_ZERO:96,KC_NUM_ONE:97,KC_NUM_TWO:98,KC_NUM_THREE:99,KC_NUM_FOUR:100,KC_NUM_FIVE:101,KC_NUM_SIX:102,KC_NUM_SEVEN:103,
KC_NUM_EIGHT:104,KC_NUM_NINE:105,KC_MULTIPLY:106,KC_PLUS:107,KC_MINUS:109,KC_PERIOD:110,KC_DIVISION:111,KC_DIVIDE:111,KC_F1:112,KC_F2:113,KC_F3:114,KC_F4:115,KC_F5:116,KC_F6:117,KC_F7:118,KC_F8:119,KC_F9:120,KC_F10:121,KC_F11:122,KC_F12:123,isSpecialKey:function(a,c){if(a>32&&a<41)return true;if(a==8||a==9||a==13||a==27)return true;if(a==45||a==46)return false;if(c.ctrlKey&&a!=this.KC_CTRL)return true;if(c.altKey&&a!=this.KC_ALT)return true;return false},isNavigationKey:function(a){if(a>32&&a<41)return true;
if(a==9||a==13||a==27)return true;return false},getFakeEvent:function(a,c){var b=new aria.DomEvent({type:a});b.type=a;b.target=c;return b}}})})();