// Generated by CoffeeScript 1.3.1
(function() {

  Aria.classDefinition({
    $classpath: 'games.shoot.controller.loading.GameTitle',
    $extends: 'games.common.text.Text',
    $implements: ['games.shoot.overlay.OverlayEntity'],
    $dependencies: ['games.shoot.utils.Environment'],
    $statics: {
      FONT_SIZE: '52px',
      FONT_COLOR: 'white',
      FONT_FAMILY: 'Game'
    },
    $constructor: function() {
      this.$Text.constructor.call(this, this.FONT_FAMILY, this.FONT_SIZE, this.FONT_COLOR, 'center', 'middle');
      this.setContent("HTML 5H007");
      return this;
    },
    $prototype: {
      draw: function(context) {
        return this.$Text.draw.call(this, this.$Environment.BOARD.WIDTH / 2, 200, context);
      }
    }
  });

}).call(this);
