// Generated by CoffeeScript 1.3.1
(function() {

  Aria.classDefinition({
    $classpath: 'games.shoot.controller.loading.InviteText',
    $extends: 'games.common.text.Text',
    $implements: ['games.shoot.overlay.OverlayEntity'],
    $dependencies: ['games.shoot.utils.Environment', 'aria.utils.Math', 'games.common.utils.UserAgent', 'games.common.sprite.BlinkingSprite'],
    $statics: {
      FONT_SIZE: '36px',
      FONT_COLOR: 'white',
      FONT_FAMILY: 'Game',
      SPEED: 0.1,
      END_Y: 400
    },
    $constructor: function() {
      var at, fakeSprite;
      this.$Text.constructor.call(this, this.FONT_FAMILY, this.FONT_SIZE, this.FONT_COLOR, 'center', 'middle');
      if (this.$UserAgent.isTouchDevice()) {
        this.setContent("Touch to Start");
      } else {
        this.setContent("Press ENTER");
      }
      this.y = this.$Environment.BOARD.HEIGHT;
      at = this;
      fakeSprite = {
        draw: function(x, y, c) {
          return at.$Text.draw.call(at, x, y, c);
        }
      };
      this.sprite = new this.$BlinkingSprite(fakeSprite, 350);
      this.sprite.setBlinking(true);
      return this;
    },
    $prototype: {
      update: function(deltaTime) {
        this.sprite.update(deltaTime);
        return this.y = Math.max(this.y - deltaTime * this.SPEED, this.END_Y);
      },
      draw: function(context) {
        return this.sprite.draw(this.$Environment.BOARD.WIDTH / 2, this.y, context);
      }
    }
  });

}).call(this);
