// Generated by CoffeeScript 1.3.1
(function() {

  Aria.classDefinition({
    $classpath: 'games.common.math.GameMath',
    $extends: 'games.common.BaseObject',
    $dependencies: ['aria.utils.Math'],
    $statics: {
      normalizeFromToWithDelta: function(from, to, delta) {
        var normalized;
        delta = Math.abs(delta);
        if (from > to) {
          normalized = Math.max(to, from - delta);
        }
        if (from < to) {
          normalized = Math.min(to, from + delta);
        }
        if (from === to) {
          normalized = to;
        }
        return normalized;
      }
    }
  });

}).call(this);
