// Generated by CoffeeScript 1.3.1
(function() {

  Aria.classDefinition({
    $classpath: 'games.common.clock.AnimationLoop',
    $extends: 'games.common.BaseObject',
    $dependencies: ['games.common.clock.BrowserAnimationHelper'],
    $constructor: function() {
      this.$BaseObject.constructor.call(this);
      this.isRunning = false;
      this.browserAnimationHelper = new this.$BrowserAnimationHelper;
      return this;
    },
    $prototype: {
      setLoopCallback: function(method, scope) {
        return this.loopCallback = {
          fn: method,
          scope: scope
        };
      },
      start: function() {
        this.isRunning = true;
        return this.loop();
      },
      loop: function() {
        if (this.isRunning) {
          return this.executeLoop();
        }
      },
      executeLoop: function() {
        this.$callback(this.loopCallback);
        return this.browserAnimationHelper.requestRepaint(this.loop, this);
      },
      stop: function() {
        this.isRunning = false;
        return this.callback = null;
      },
      isOn: function() {
        return this.isRunning;
      }
    },
    $destructor: function() {
      this.stop();
      return this.browserAnimationHelper.$dispose();
    }
  });

}).call(this);
