// Generated by CoffeeScript 1.3.1
(function() {

  Aria.interfaceDefinition({
    $classpath: 'games.common.engine.Engine',
    $constructor: function(context, inputRecorder, animationLoop, timer) {},
    $interface: {
      addEntity: function() {},
      update: function() {},
      draw: function() {},
      getTimer: function() {}
    }
  });

}).call(this);
