// Generated by CoffeeScript 1.3.1
(function() {

  Aria.classDefinition({
    $classpath: 'games.common.utils.UserAgent',
    $extends: 'games.common.BaseObject',
    $statics: {
      isTouchDevice: function() {
        return this.isTouchAgent(this.getUserAgent());
      },
      isTouchAgent: function(agent) {
        return agent.match(/ipad|iphone|android/ig);
      },
      getUserAgent: function() {
        return window.navigator.userAgent;
      }
    }
  });

}).call(this);
