// Generated by CoffeeScript 1.3.1
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Aria.classDefinition({
    $classpath: 'games.common.sprite.SpriteBuilder',
    $dependencies: ['games.common.sprite.Sprite'],
    $singleton: true,
    $constructor: function() {
      this.cache = new Object;
      return this;
    },
    $prototype: {
      build: function(url, transform) {
        var asset, key, sprite;
        key = "" + url + "__" + transform.angle + "__" + transform.scale.x + "__" + transform.scale.y;
        if (__indexOf.call(this.cache, key) >= 0) {
          return this.cache[key];
        } else {
          asset = games.shoot.AssetManager.getAsset(url);
          sprite = new games.common.sprite.Sprite(asset);
          sprite.rotate(transform.angle);
          sprite.scale(transform.scale.x, transform.scale.y);
          return this.cache[key] = sprite;
        }
      }
    }
  });

}).call(this);
